{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "b058902c-6a5c-4c7e-9e62-a2973d4b77af",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting tfx\n",
      "  Obtaining dependency information for tfx from https://files.pythonhosted.org/packages/3c/e1/919574a8d34382c09ce0c74398dfa615d368d210741773263fa716ffcda6/tfx-1.14.0-py3-none-any.whl.metadata\n",
      "  Using cached tfx-1.14.0-py3-none-any.whl.metadata (22 kB)\n",
      "Collecting ml-pipelines-sdk==1.14.0 (from tfx)\n",
      "  Obtaining dependency information for ml-pipelines-sdk==1.14.0 from https://files.pythonhosted.org/packages/45/90/8b25072e398f8772521374c5d4315a74cb7bfd30aaa7ab3e399d95d4faa4/ml_pipelines_sdk-1.14.0-py3-none-any.whl.metadata\n",
      "  Using cached ml_pipelines_sdk-1.14.0-py3-none-any.whl.metadata (2.3 kB)\n",
      "Requirement already satisfied: absl-py<2.0.0,>=0.9 in /opt/conda/lib/python3.8/site-packages (from tfx) (0.12.0)\n",
      "Collecting ml-metadata<1.15.0,>=1.14.0 (from tfx)\n",
      "  Obtaining dependency information for ml-metadata<1.15.0,>=1.14.0 from https://files.pythonhosted.org/packages/e1/59/5b44a61cfdd52f52a0ac9402b3fbd08fe23cfb8d7a4c84a44dd7002edc3a/ml_metadata-1.14.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata\n",
      "  Using cached ml_metadata-1.14.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.9 kB)\n",
      "Collecting packaging<21,>=20 (from tfx)\n",
      "  Using cached packaging-20.9-py2.py3-none-any.whl (40 kB)\n",
      "Collecting portpicker<2,>=1.3.1 (from tfx)\n",
      "  Obtaining dependency information for portpicker<2,>=1.3.1 from https://files.pythonhosted.org/packages/32/2d/440e4d7041fff89f28f483733eb617127aa866135c2dc719e05893f089e1/portpicker-1.6.0-py3-none-any.whl.metadata\n",
      "  Using cached portpicker-1.6.0-py3-none-any.whl.metadata (1.5 kB)\n",
      "Collecting protobuf<5,>=3.20.3 (from tfx)\n",
      "  Obtaining dependency information for protobuf<5,>=3.20.3 from https://files.pythonhosted.org/packages/bb/c3/6a06208ecf0934ecaf509b51c52a6cf688586f54ae81ac65c56124571494/protobuf-4.24.3-cp37-abi3-manylinux2014_x86_64.whl.metadata\n",
      "  Using cached protobuf-4.24.3-cp37-abi3-manylinux2014_x86_64.whl.metadata (540 bytes)\n",
      "Collecting docker<5,>=4.1 (from tfx)\n",
      "  Using cached docker-4.4.4-py2.py3-none-any.whl (147 kB)\n",
      "Collecting google-apitools<1,>=0.5 (from tfx)\n",
      "  Using cached google_apitools-0.5.32-py3-none-any.whl (135 kB)\n",
      "Requirement already satisfied: google-api-python-client<2,>=1.8 in /opt/conda/lib/python3.8/site-packages (from tfx) (1.12.11)\n",
      "Requirement already satisfied: jinja2<4,>=2.7.3 in /opt/conda/lib/python3.8/site-packages (from tfx) (3.1.2)\n",
      "Requirement already satisfied: typing-extensions<5,>=3.10.0.2 in /home/chase/.local/lib/python3.8/site-packages (from tfx) (3.10.0.2)\n",
      "Collecting apache-beam[gcp]<3,>=2.47 (from tfx)\n",
      "  Obtaining dependency information for apache-beam[gcp]<3,>=2.47 from https://files.pythonhosted.org/packages/47/9c/ec3d6609d396ffd1b6f415e6bedb78874b837e3c47ab1d4472d2b0c5d899/apache_beam-2.50.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata\n",
      "  Using cached apache_beam-2.50.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.0 kB)\n",
      "Requirement already satisfied: attrs<22,>=19.3.0 in /opt/conda/lib/python3.8/site-packages (from tfx) (20.3.0)\n",
      "Requirement already satisfied: click<9,>=7 in /opt/conda/lib/python3.8/site-packages (from tfx) (8.1.3)\n",
      "Requirement already satisfied: google-api-core<3 in /home/chase/.local/lib/python3.8/site-packages (from tfx) (2.10.2)\n",
      "Collecting google-cloud-aiplatform<2,>=1.6.2 (from tfx)\n",
      "  Obtaining dependency information for google-cloud-aiplatform<2,>=1.6.2 from https://files.pythonhosted.org/packages/d3/66/10a048f9327fc9efb16233ab009960dc8717327e3359e12ca94f038b22b1/google_cloud_aiplatform-1.33.1-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_cloud_aiplatform-1.33.1-py2.py3-none-any.whl.metadata (27 kB)\n",
      "Collecting google-cloud-bigquery<3,>=2.26.0 (from tfx)\n",
      "  Using cached google_cloud_bigquery-2.34.4-py2.py3-none-any.whl (206 kB)\n",
      "Requirement already satisfied: grpcio<2,>=1.28.1 in /opt/conda/lib/python3.8/site-packages (from tfx) (1.54.0)\n",
      "Collecting keras-tuner<2,>=1.0.4 (from tfx)\n",
      "  Obtaining dependency information for keras-tuner<2,>=1.0.4 from https://files.pythonhosted.org/packages/03/e6/871ded93d99ee17d022a28752f8328f895c2e71fc7b478f861dc987c9b1a/keras_tuner-1.4.2-py3-none-any.whl.metadata\n",
      "  Using cached keras_tuner-1.4.2-py3-none-any.whl.metadata (5.4 kB)\n",
      "Requirement already satisfied: kubernetes<13,>=10.0.1 in /opt/conda/lib/python3.8/site-packages (from tfx) (12.0.1)\n",
      "Requirement already satisfied: numpy<2,>=1.16 in /opt/conda/lib/python3.8/site-packages (from tfx) (1.22.4)\n",
      "Collecting pyarrow<11,>=10 (from tfx)\n",
      "  Using cached pyarrow-10.0.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (36.0 MB)\n",
      "Collecting pyyaml<7,>=6 (from tfx)\n",
      "  Obtaining dependency information for pyyaml<7,>=6 from https://files.pythonhosted.org/packages/c8/6b/6600ac24725c7388255b2f5add93f91e58a5d7efaf4af244fdbcc11a541b/PyYAML-6.0.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata\n",
      "  Using cached PyYAML-6.0.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.1 kB)\n",
      "Collecting tensorflow<2.14,>=2.13.0 (from tfx)\n",
      "  Obtaining dependency information for tensorflow<2.14,>=2.13.0 from https://files.pythonhosted.org/packages/c2/20/b15abac0be474f12cf51a104c9dd935b053081b502c103e9e947e8be7b84/tensorflow-2.13.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata\n",
      "  Using cached tensorflow-2.13.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.4 kB)\n",
      "Collecting tensorflow-hub<0.14,>=0.9.0 (from tfx)\n",
      "  Using cached tensorflow_hub-0.13.0-py2.py3-none-any.whl (100 kB)\n",
      "Collecting tensorflow-data-validation<1.15.0,>=1.14.0 (from tfx)\n",
      "  Obtaining dependency information for tensorflow-data-validation<1.15.0,>=1.14.0 from https://files.pythonhosted.org/packages/d6/a6/0ee70ba25674199dc20226f64719bf84b9ce3b3aff2c05e7a765bcdc273c/tensorflow_data_validation-1.14.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata\n",
      "  Using cached tensorflow_data_validation-1.14.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (18 kB)\n",
      "Collecting tensorflow-model-analysis<0.46.0,>=0.45.0 (from tfx)\n",
      "  Obtaining dependency information for tensorflow-model-analysis<0.46.0,>=0.45.0 from https://files.pythonhosted.org/packages/35/56/9a2a677e178caa313fd3cc2ddc7df8558339504487baf1a726e7011dcbd6/tensorflow_model_analysis-0.45.0-py3-none-any.whl.metadata\n",
      "  Using cached tensorflow_model_analysis-0.45.0-py3-none-any.whl.metadata (19 kB)\n",
      "Collecting tensorflow-serving-api!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,<3,>=1.15 (from tfx)\n",
      "  Obtaining dependency information for tensorflow-serving-api!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,<3,>=1.15 from https://files.pythonhosted.org/packages/71/fe/4004906ca558255673fab41a1bb2189ca6454417487a8608100677c8cc15/tensorflow_serving_api-2.13.0-py2.py3-none-any.whl.metadata\n",
      "  Using cached tensorflow_serving_api-2.13.0-py2.py3-none-any.whl.metadata (1.8 kB)\n",
      "Collecting tensorflow-transform<1.15.0,>=1.14.0 (from tfx)\n",
      "  Obtaining dependency information for tensorflow-transform<1.15.0,>=1.14.0 from https://files.pythonhosted.org/packages/91/60/1024ca9eb74e1f6a79a43064562f60efb0cc3b5e5d0dd22d81c065c3b8a1/tensorflow_transform-1.14.0-py3-none-any.whl.metadata\n",
      "  Using cached tensorflow_transform-1.14.0-py3-none-any.whl.metadata (12 kB)\n",
      "Collecting tfx-bsl<1.15.0,>=1.14.0 (from tfx)\n",
      "  Obtaining dependency information for tfx-bsl<1.15.0,>=1.14.0 from https://files.pythonhosted.org/packages/37/8c/3534124ad7cacc7cd128708fc629f52cd6e58e581f81c15bff13f6e916cb/tfx_bsl-1.14.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata\n",
      "  Using cached tfx_bsl-1.14.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (10 kB)\n",
      "Requirement already satisfied: six in /opt/conda/lib/python3.8/site-packages (from absl-py<2.0.0,>=0.9->tfx) (1.16.0)\n",
      "Collecting crcmod<2.0,>=1.7 (from apache-beam[gcp]<3,>=2.47->tfx)\n",
      "  Using cached crcmod-1.7-py3-none-any.whl\n",
      "Collecting orjson<4.0 (from apache-beam[gcp]<3,>=2.47->tfx)\n",
      "  Obtaining dependency information for orjson<4.0 from https://files.pythonhosted.org/packages/cc/b4/324754a9e255295c0b5966f78999822e180a0fa2c22fd96edefac9dd8313/orjson-3.9.7-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata\n",
      "  Using cached orjson-3.9.7-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (49 kB)\n",
      "Collecting dill<0.3.2,>=0.3.1.1 (from apache-beam[gcp]<3,>=2.47->tfx)\n",
      "  Using cached dill-0.3.1.1-py3-none-any.whl\n",
      "Collecting cloudpickle~=2.2.1 (from apache-beam[gcp]<3,>=2.47->tfx)\n",
      "  Using cached cloudpickle-2.2.1-py3-none-any.whl (25 kB)\n",
      "Requirement already satisfied: fastavro<2,>=0.23.6 in /opt/conda/lib/python3.8/site-packages (from apache-beam[gcp]<3,>=2.47->tfx) (1.7.3)\n",
      "Collecting fasteners<1.0,>=0.3 (from apache-beam[gcp]<3,>=2.47->tfx)\n",
      "  Obtaining dependency information for fasteners<1.0,>=0.3 from https://files.pythonhosted.org/packages/61/bf/fd60001b3abc5222d8eaa4a204cd8c0ae78e75adc688f33ce4bf25b7fafa/fasteners-0.19-py3-none-any.whl.metadata\n",
      "  Using cached fasteners-0.19-py3-none-any.whl.metadata (4.9 kB)\n",
      "Collecting hdfs<3.0.0,>=2.1.0 (from apache-beam[gcp]<3,>=2.47->tfx)\n",
      "  Using cached hdfs-2.7.2-py3-none-any.whl\n",
      "Requirement already satisfied: httplib2<0.23.0,>=0.8 in /opt/conda/lib/python3.8/site-packages (from apache-beam[gcp]<3,>=2.47->tfx) (0.22.0)\n",
      "Collecting objsize<0.7.0,>=0.6.1 (from apache-beam[gcp]<3,>=2.47->tfx)\n",
      "  Using cached objsize-0.6.1-py3-none-any.whl (9.3 kB)\n",
      "Collecting pymongo<5.0.0,>=3.8.0 (from apache-beam[gcp]<3,>=2.47->tfx)\n",
      "  Obtaining dependency information for pymongo<5.0.0,>=3.8.0 from https://files.pythonhosted.org/packages/bf/b7/63cebc24f4690b85d0c91fe11a32ad14e791ff499f4054cde8f1a4ea08dc/pymongo-4.5.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata\n",
      "  Using cached pymongo-4.5.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (22 kB)\n",
      "Requirement already satisfied: proto-plus<2,>=1.7.1 in /opt/conda/lib/python3.8/site-packages (from apache-beam[gcp]<3,>=2.47->tfx) (1.22.2)\n",
      "Collecting protobuf<5,>=3.20.3 (from tfx)\n",
      "  Obtaining dependency information for protobuf<5,>=3.20.3 from https://files.pythonhosted.org/packages/01/cb/445b3e465abdb8042a41957dc8f60c54620dc7540dbcf9b458a921531ca2/protobuf-4.23.4-cp37-abi3-manylinux2014_x86_64.whl.metadata\n",
      "  Using cached protobuf-4.23.4-cp37-abi3-manylinux2014_x86_64.whl.metadata (540 bytes)\n",
      "Collecting pydot<2,>=1.2.0 (from apache-beam[gcp]<3,>=2.47->tfx)\n",
      "  Using cached pydot-1.4.2-py2.py3-none-any.whl (21 kB)\n",
      "Requirement already satisfied: python-dateutil<3,>=2.8.0 in /opt/conda/lib/python3.8/site-packages (from apache-beam[gcp]<3,>=2.47->tfx) (2.8.2)\n",
      "Requirement already satisfied: pytz>=2018.3 in /opt/conda/lib/python3.8/site-packages (from apache-beam[gcp]<3,>=2.47->tfx) (2022.7.1)\n",
      "Collecting regex>=2020.6.8 (from apache-beam[gcp]<3,>=2.47->tfx)\n",
      "  Obtaining dependency information for regex>=2020.6.8 from https://files.pythonhosted.org/packages/1f/5c/374ac3fa3c7ed9a967ad273a5e841897ef6b10aa6aad938ff10717a3e2a3/regex-2023.8.8-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata\n",
      "  Using cached regex-2023.8.8-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (40 kB)\n",
      "Requirement already satisfied: requests<3.0.0,>=2.24.0 in /opt/conda/lib/python3.8/site-packages (from apache-beam[gcp]<3,>=2.47->tfx) (2.28.2)\n",
      "Requirement already satisfied: zstandard<1,>=0.18.0 in /opt/conda/lib/python3.8/site-packages (from apache-beam[gcp]<3,>=2.47->tfx) (0.19.0)\n",
      "Requirement already satisfied: cachetools<6,>=3.1.0 in /home/chase/.local/lib/python3.8/site-packages (from apache-beam[gcp]<3,>=2.47->tfx) (4.2.4)\n",
      "Collecting google-apitools<1,>=0.5 (from tfx)\n",
      "  Using cached google_apitools-0.5.31-py3-none-any.whl\n",
      "Requirement already satisfied: google-auth<3,>=1.18.0 in /home/chase/.local/lib/python3.8/site-packages (from apache-beam[gcp]<3,>=2.47->tfx) (1.35.0)\n",
      "Requirement already satisfied: google-auth-httplib2<0.2.0,>=0.1.0 in /opt/conda/lib/python3.8/site-packages (from apache-beam[gcp]<3,>=2.47->tfx) (0.1.0)\n",
      "Collecting google-cloud-datastore<3,>=2.0.0 (from apache-beam[gcp]<3,>=2.47->tfx)\n",
      "  Obtaining dependency information for google-cloud-datastore<3,>=2.0.0 from https://files.pythonhosted.org/packages/e6/e3/9e19e26b4fc61aa64a73d097c9e5ce3b4cbb62d7d0ea2c0554b2105b54d6/google_cloud_datastore-2.18.0-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_cloud_datastore-2.18.0-py2.py3-none-any.whl.metadata (5.5 kB)\n",
      "Collecting google-cloud-pubsub<3,>=2.1.0 (from apache-beam[gcp]<3,>=2.47->tfx)\n",
      "  Obtaining dependency information for google-cloud-pubsub<3,>=2.1.0 from https://files.pythonhosted.org/packages/d2/58/fbdedd07206514f09f029458d95d391829b09399c1459d8892e6e20022d1/google_cloud_pubsub-2.18.4-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_cloud_pubsub-2.18.4-py2.py3-none-any.whl.metadata (9.2 kB)\n",
      "Collecting google-cloud-pubsublite<2,>=1.2.0 (from apache-beam[gcp]<3,>=2.47->tfx)\n",
      "  Obtaining dependency information for google-cloud-pubsublite<2,>=1.2.0 from https://files.pythonhosted.org/packages/2d/d6/91f605fc67e9d0b4e419c4f291adff15c2f241bf3d70abe8068688599d60/google_cloud_pubsublite-1.8.3-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_cloud_pubsublite-1.8.3-py2.py3-none-any.whl.metadata (5.5 kB)\n",
      "Collecting google-cloud-bigquery-storage<3,>=2.6.3 (from apache-beam[gcp]<3,>=2.47->tfx)\n",
      "  Obtaining dependency information for google-cloud-bigquery-storage<3,>=2.6.3 from https://files.pythonhosted.org/packages/83/eb/e5016412a9c6ac26b46480f83d58112b99b48c0e38ae040b46f8795dea6f/google_cloud_bigquery_storage-2.22.0-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_cloud_bigquery_storage-2.22.0-py2.py3-none-any.whl.metadata (5.4 kB)\n",
      "Requirement already satisfied: google-cloud-core<3,>=2.0.0 in /opt/conda/lib/python3.8/site-packages (from apache-beam[gcp]<3,>=2.47->tfx) (2.3.2)\n",
      "Collecting google-cloud-bigtable<3,>=2.19.0 (from apache-beam[gcp]<3,>=2.47->tfx)\n",
      "  Obtaining dependency information for google-cloud-bigtable<3,>=2.19.0 from https://files.pythonhosted.org/packages/f1/2e/fcdd3aed46825c04bc93c0223fff674059e6a789cfda5374948bea1a3f6e/google_cloud_bigtable-2.21.0-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_cloud_bigtable-2.21.0-py2.py3-none-any.whl.metadata (5.1 kB)\n",
      "Collecting google-cloud-spanner<4,>=3.0.0 (from apache-beam[gcp]<3,>=2.47->tfx)\n",
      "  Obtaining dependency information for google-cloud-spanner<4,>=3.0.0 from https://files.pythonhosted.org/packages/fd/77/527bbb6c103ef5e8e0d49d8000e337d3ce4ed66a373af915b0170012de30/google_cloud_spanner-3.40.1-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_cloud_spanner-3.40.1-py2.py3-none-any.whl.metadata (10 kB)\n",
      "Collecting google-cloud-dlp<4,>=3.0.0 (from apache-beam[gcp]<3,>=2.47->tfx)\n",
      "  Obtaining dependency information for google-cloud-dlp<4,>=3.0.0 from https://files.pythonhosted.org/packages/9a/2c/5a62598d1696246c056e512ac69983e0d736cd2cd2ac1107075743a4ec48/google_cloud_dlp-3.12.3-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_cloud_dlp-3.12.3-py2.py3-none-any.whl.metadata (5.2 kB)\n",
      "Collecting google-cloud-language<3,>=2.0 (from apache-beam[gcp]<3,>=2.47->tfx)\n",
      "  Obtaining dependency information for google-cloud-language<3,>=2.0 from https://files.pythonhosted.org/packages/19/4c/8a42006ec29f26d1d0f47f5fdebe7138a700eda8e3668d53ffcb55c9a774/google_cloud_language-2.11.1-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_cloud_language-2.11.1-py2.py3-none-any.whl.metadata (5.3 kB)\n",
      "Collecting google-cloud-videointelligence<3,>=2.0 (from apache-beam[gcp]<3,>=2.47->tfx)\n",
      "  Obtaining dependency information for google-cloud-videointelligence<3,>=2.0 from https://files.pythonhosted.org/packages/ca/0e/ce99f6c36d5e7ccbc5827d714a947da5b864a30e060f2e5dddad4166f663/google_cloud_videointelligence-2.11.4-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_cloud_videointelligence-2.11.4-py2.py3-none-any.whl.metadata (5.6 kB)\n",
      "Collecting google-cloud-vision<4,>=2 (from apache-beam[gcp]<3,>=2.47->tfx)\n",
      "  Obtaining dependency information for google-cloud-vision<4,>=2 from https://files.pythonhosted.org/packages/14/16/e3ea36b6989e0cff58c2cc38261b9b5133a58d1fb08d64fb85fc552f3466/google_cloud_vision-3.4.4-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_cloud_vision-3.4.4-py2.py3-none-any.whl.metadata (6.2 kB)\n",
      "Collecting google-cloud-recommendations-ai<0.11.0,>=0.1.0 (from apache-beam[gcp]<3,>=2.47->tfx)\n",
      "  Obtaining dependency information for google-cloud-recommendations-ai<0.11.0,>=0.1.0 from https://files.pythonhosted.org/packages/f9/7f/c6554fcbc09a861e11214df359c1d048791c8a2d6b8909be023ba5fe0997/google_cloud_recommendations_ai-0.10.5-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_cloud_recommendations_ai-0.10.5-py2.py3-none-any.whl.metadata (5.2 kB)\n",
      "Requirement already satisfied: websocket-client>=0.32.0 in /opt/conda/lib/python3.8/site-packages (from docker<5,>=4.1->tfx) (1.5.1)\n",
      "Requirement already satisfied: googleapis-common-protos<2.0dev,>=1.56.2 in /opt/conda/lib/python3.8/site-packages (from google-api-core<3->tfx) (1.59.0)\n",
      "Requirement already satisfied: uritemplate<4dev,>=3.0.0 in /opt/conda/lib/python3.8/site-packages (from google-api-python-client<2,>=1.8->tfx) (3.0.1)\n",
      "Collecting oauth2client>=1.4.12 (from google-apitools<1,>=0.5->tfx)\n",
      "  Using cached oauth2client-4.1.3-py2.py3-none-any.whl (98 kB)\n",
      "Requirement already satisfied: google-cloud-storage<3.0.0dev,>=1.32.0 in /home/chase/.local/lib/python3.8/site-packages (from google-cloud-aiplatform<2,>=1.6.2->tfx) (1.44.0)\n",
      "Collecting google-cloud-resource-manager<3.0.0dev,>=1.3.3 (from google-cloud-aiplatform<2,>=1.6.2->tfx)\n",
      "  Obtaining dependency information for google-cloud-resource-manager<3.0.0dev,>=1.3.3 from https://files.pythonhosted.org/packages/8b/9c/6807473e69fddc9bf33413b7db966fbcfeb0deade2f5ed324cef2b98ec16/google_cloud_resource_manager-1.10.4-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_cloud_resource_manager-1.10.4-py2.py3-none-any.whl.metadata (5.2 kB)\n",
      "Collecting shapely<2.0.0 (from google-cloud-aiplatform<2,>=1.6.2->tfx)\n",
      "  Using cached Shapely-1.8.5.post1-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (2.1 MB)\n",
      "Requirement already satisfied: google-resumable-media<3.0dev,>=0.6.0 in /opt/conda/lib/python3.8/site-packages (from google-cloud-bigquery<3,>=2.26.0->tfx) (2.4.1)\n",
      "Collecting protobuf<5,>=3.20.3 (from tfx)\n",
      "  Using cached protobuf-3.20.3-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.whl (1.0 MB)\n",
      "Requirement already satisfied: MarkupSafe>=2.0 in /opt/conda/lib/python3.8/site-packages (from jinja2<4,>=2.7.3->tfx) (2.1.2)\n",
      "Collecting keras-core (from keras-tuner<2,>=1.0.4->tfx)\n",
      "  Obtaining dependency information for keras-core from https://files.pythonhosted.org/packages/33/18/5280fbfd70485fae8088a2f44647ea0d82c7dc9b80635ae2e7c578f785e0/keras_core-0.1.5-py3-none-any.whl.metadata\n",
      "  Using cached keras_core-0.1.5-py3-none-any.whl.metadata (4.0 kB)\n",
      "Collecting kt-legacy (from keras-tuner<2,>=1.0.4->tfx)\n",
      "  Using cached kt_legacy-1.0.5-py3-none-any.whl (9.6 kB)\n",
      "Requirement already satisfied: certifi>=14.05.14 in /opt/conda/lib/python3.8/site-packages (from kubernetes<13,>=10.0.1->tfx) (2022.12.7)\n",
      "Requirement already satisfied: setuptools>=21.0.0 in /opt/conda/lib/python3.8/site-packages (from kubernetes<13,>=10.0.1->tfx) (67.7.1)\n",
      "Requirement already satisfied: requests-oauthlib in /opt/conda/lib/python3.8/site-packages (from kubernetes<13,>=10.0.1->tfx) (1.3.1)\n",
      "Requirement already satisfied: urllib3>=1.24.2 in /opt/conda/lib/python3.8/site-packages (from kubernetes<13,>=10.0.1->tfx) (1.26.15)\n",
      "Requirement already satisfied: pyparsing>=2.0.2 in /opt/conda/lib/python3.8/site-packages (from packaging<21,>=20->tfx) (3.0.9)\n",
      "Requirement already satisfied: psutil in /opt/conda/lib/python3.8/site-packages (from portpicker<2,>=1.3.1->tfx) (5.9.5)\n",
      "Collecting absl-py<2.0.0,>=0.9 (from tfx)\n",
      "  Using cached absl_py-1.4.0-py3-none-any.whl (126 kB)\n",
      "Requirement already satisfied: astunparse>=1.6.0 in /opt/conda/lib/python3.8/site-packages (from tensorflow<2.14,>=2.13.0->tfx) (1.6.3)\n",
      "Collecting flatbuffers>=23.1.21 (from tensorflow<2.14,>=2.13.0->tfx)\n",
      "  Obtaining dependency information for flatbuffers>=23.1.21 from https://files.pythonhosted.org/packages/6f/12/d5c79ee252793ffe845d58a913197bfa02ae9a0b5c9bc3dc4b58d477b9e7/flatbuffers-23.5.26-py2.py3-none-any.whl.metadata\n",
      "  Using cached flatbuffers-23.5.26-py2.py3-none-any.whl.metadata (850 bytes)\n",
      "Requirement already satisfied: gast<=0.4.0,>=0.2.1 in /opt/conda/lib/python3.8/site-packages (from tensorflow<2.14,>=2.13.0->tfx) (0.4.0)\n",
      "Requirement already satisfied: google-pasta>=0.1.1 in /opt/conda/lib/python3.8/site-packages (from tensorflow<2.14,>=2.13.0->tfx) (0.2.0)\n",
      "Requirement already satisfied: h5py>=2.9.0 in /opt/conda/lib/python3.8/site-packages (from tensorflow<2.14,>=2.13.0->tfx) (3.8.0)\n",
      "Collecting keras<2.14,>=2.13.1 (from tensorflow<2.14,>=2.13.0->tfx)\n",
      "  Obtaining dependency information for keras<2.14,>=2.13.1 from https://files.pythonhosted.org/packages/2e/f3/19da7511b45e80216cbbd9467137b2d28919c58ba1ccb971435cb631e470/keras-2.13.1-py3-none-any.whl.metadata\n",
      "  Using cached keras-2.13.1-py3-none-any.whl.metadata (2.4 kB)\n",
      "Requirement already satisfied: libclang>=13.0.0 in /opt/conda/lib/python3.8/site-packages (from tensorflow<2.14,>=2.13.0->tfx) (16.0.0)\n",
      "Requirement already satisfied: opt-einsum>=2.3.2 in /opt/conda/lib/python3.8/site-packages (from tensorflow<2.14,>=2.13.0->tfx) (3.3.0)\n",
      "Collecting tensorboard<2.14,>=2.13 (from tensorflow<2.14,>=2.13.0->tfx)\n",
      "  Using cached tensorboard-2.13.0-py3-none-any.whl (5.6 MB)\n",
      "Collecting tensorflow-estimator<2.14,>=2.13.0 (from tensorflow<2.14,>=2.13.0->tfx)\n",
      "  Obtaining dependency information for tensorflow-estimator<2.14,>=2.13.0 from https://files.pythonhosted.org/packages/72/5c/c318268d96791c6222ad7df1651bbd1b2409139afeb6f468c0f327177016/tensorflow_estimator-2.13.0-py2.py3-none-any.whl.metadata\n",
      "  Using cached tensorflow_estimator-2.13.0-py2.py3-none-any.whl.metadata (1.3 kB)\n",
      "Requirement already satisfied: termcolor>=1.1.0 in /opt/conda/lib/python3.8/site-packages (from tensorflow<2.14,>=2.13.0->tfx) (2.2.0)\n",
      "Requirement already satisfied: wrapt>=1.11.0 in /opt/conda/lib/python3.8/site-packages (from tensorflow<2.14,>=2.13.0->tfx) (1.15.0)\n",
      "Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /opt/conda/lib/python3.8/site-packages (from tensorflow<2.14,>=2.13.0->tfx) (0.32.0)\n",
      "Requirement already satisfied: joblib>=1.2.0 in /opt/conda/lib/python3.8/site-packages (from tensorflow-data-validation<1.15.0,>=1.14.0->tfx) (1.2.0)\n",
      "Requirement already satisfied: pandas<2,>=1.0 in /opt/conda/lib/python3.8/site-packages (from tensorflow-data-validation<1.15.0,>=1.14.0->tfx) (1.5.3)\n",
      "Collecting pyfarmhash<0.4,>=0.2.2 (from tensorflow-data-validation<1.15.0,>=1.14.0->tfx)\n",
      "  Using cached pyfarmhash-0.3.2.tar.gz (99 kB)\n",
      "  Preparing metadata (setup.py) ... \u001b[?25ldone\n",
      "\u001b[?25hCollecting tensorflow-metadata<1.15,>=1.14.0 (from tensorflow-data-validation<1.15.0,>=1.14.0->tfx)\n",
      "  Obtaining dependency information for tensorflow-metadata<1.15,>=1.14.0 from https://files.pythonhosted.org/packages/41/23/3705c7139886c079ef4c0e3be56a5a1fb90e9ee413a4b7caaee0ee0ea6fe/tensorflow_metadata-1.14.0-py3-none-any.whl.metadata\n",
      "  Using cached tensorflow_metadata-1.14.0-py3-none-any.whl.metadata (2.1 kB)\n",
      "Collecting ipython<8,>=7 (from tensorflow-model-analysis<0.46.0,>=0.45.0->tfx)\n",
      "  Using cached ipython-7.34.0-py3-none-any.whl (793 kB)\n",
      "Requirement already satisfied: ipywidgets<8,>=7 in /opt/conda/lib/python3.8/site-packages (from tensorflow-model-analysis<0.46.0,>=0.45.0->tfx) (7.6.3)\n",
      "Requirement already satisfied: pillow>=9.4.0 in /opt/conda/lib/python3.8/site-packages (from tensorflow-model-analysis<0.46.0,>=0.45.0->tfx) (9.5.0)\n",
      "Requirement already satisfied: scipy<2,>=1.4.1 in /opt/conda/lib/python3.8/site-packages (from tensorflow-model-analysis<0.46.0,>=0.45.0->tfx) (1.7.0)\n",
      "Requirement already satisfied: wheel<1.0,>=0.23.0 in /opt/conda/lib/python3.8/site-packages (from astunparse>=1.6.0->tensorflow<2.14,>=2.13.0->tfx) (0.40.0)\n",
      "Collecting grpcio-status<2.0dev,>=1.33.2 (from google-api-core<3->tfx)\n",
      "  Obtaining dependency information for grpcio-status<2.0dev,>=1.33.2 from https://files.pythonhosted.org/packages/f6/48/2bcf11bc2df159564eac099ea38d80663d291a56fa2f2f561d08bf083dfa/grpcio_status-1.58.0-py3-none-any.whl.metadata\n",
      "  Using cached grpcio_status-1.58.0-py3-none-any.whl.metadata (1.3 kB)\n",
      "Requirement already satisfied: pyasn1-modules>=0.2.1 in /opt/conda/lib/python3.8/site-packages (from google-auth<3,>=1.18.0->apache-beam[gcp]<3,>=2.47->tfx) (0.3.0)\n",
      "Requirement already satisfied: rsa<5,>=3.1.4 in /opt/conda/lib/python3.8/site-packages (from google-auth<3,>=1.18.0->apache-beam[gcp]<3,>=2.47->tfx) (4.9)\n",
      "INFO: pip is looking at multiple versions of google-cloud-bigquery-storage to determine which version is compatible with other requirements. This could take a while.\n",
      "Collecting google-cloud-bigquery-storage<3,>=2.6.3 (from apache-beam[gcp]<3,>=2.47->tfx)\n",
      "  Obtaining dependency information for google-cloud-bigquery-storage<3,>=2.6.3 from https://files.pythonhosted.org/packages/cb/82/ae60117e4d91ffd31cdd7bcc5b15d3d98088e6b2b461f278fa702d792f11/google_cloud_bigquery_storage-2.21.0-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_cloud_bigquery_storage-2.21.0-py2.py3-none-any.whl.metadata (5.4 kB)\n",
      "  Obtaining dependency information for google-cloud-bigquery-storage<3,>=2.6.3 from https://files.pythonhosted.org/packages/69/c2/884ba8fee144401c3b8fb652643a2a976f0aa1bf33dc746d6ad37175de58/google_cloud_bigquery_storage-2.20.0-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_cloud_bigquery_storage-2.20.0-py2.py3-none-any.whl.metadata (5.4 kB)\n",
      "  Using cached google_cloud_bigquery_storage-2.19.1-py2.py3-none-any.whl (190 kB)\n",
      "  Using cached google_cloud_bigquery_storage-2.19.0-py2.py3-none-any.whl (190 kB)\n",
      "  Using cached google_cloud_bigquery_storage-2.18.1-py2.py3-none-any.whl (189 kB)\n",
      "  Using cached google_cloud_bigquery_storage-2.18.0-py2.py3-none-any.whl (187 kB)\n",
      "  Using cached google_cloud_bigquery_storage-2.17.0-py2.py3-none-any.whl (187 kB)\n",
      "INFO: pip is still looking at multiple versions of google-cloud-bigquery-storage to determine which version is compatible with other requirements. This could take a while.\n",
      "  Using cached google_cloud_bigquery_storage-2.16.2-py2.py3-none-any.whl (185 kB)\n",
      "INFO: pip is looking at multiple versions of google-cloud-bigtable to determine which version is compatible with other requirements. This could take a while.\n",
      "Collecting google-cloud-bigtable<3,>=2.19.0 (from apache-beam[gcp]<3,>=2.47->tfx)\n",
      "  Obtaining dependency information for google-cloud-bigtable<3,>=2.19.0 from https://files.pythonhosted.org/packages/d0/78/72abdedf8dd216060c38df6519077420a3848416e23ba635bc844bc4b038/google_cloud_bigtable-2.20.0-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_cloud_bigtable-2.20.0-py2.py3-none-any.whl.metadata (5.1 kB)\n",
      "  Obtaining dependency information for google-cloud-bigtable<3,>=2.19.0 from https://files.pythonhosted.org/packages/e2/7f/afbc27bcaa95685e1c3bcc448b8f0251c7bdcdb00117312d64a0f17e0b98/google_cloud_bigtable-2.19.0-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_cloud_bigtable-2.19.0-py2.py3-none-any.whl.metadata (5.1 kB)\n",
      "INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.\n",
      "Collecting google-cloud-bigquery-storage<3,>=2.6.3 (from apache-beam[gcp]<3,>=2.47->tfx)\n",
      "  Using cached google_cloud_bigquery_storage-2.16.1-py2.py3-none-any.whl (185 kB)\n",
      "  Using cached google_cloud_bigquery_storage-2.16.0-py2.py3-none-any.whl (185 kB)\n",
      "INFO: pip is still looking at multiple versions of google-cloud-bigtable to determine which version is compatible with other requirements. This could take a while.\n",
      "  Using cached google_cloud_bigquery_storage-2.15.0-py2.py3-none-any.whl (182 kB)\n",
      "  Using cached google_cloud_bigquery_storage-2.14.2-py2.py3-none-any.whl (182 kB)\n",
      "INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.\n",
      "  Using cached google_cloud_bigquery_storage-2.14.1-py2.py3-none-any.whl (181 kB)\n",
      "  Using cached google_cloud_bigquery_storage-2.14.0-py2.py3-none-any.whl (181 kB)\n",
      "  Using cached google_cloud_bigquery_storage-2.13.2-py2.py3-none-any.whl (180 kB)\n",
      "  Using cached google_cloud_bigquery_storage-2.13.1-py2.py3-none-any.whl (180 kB)\n",
      "  Using cached google_cloud_bigquery_storage-2.13.0-py2.py3-none-any.whl (179 kB)\n",
      "  Using cached google_cloud_bigquery_storage-2.12.0-py2.py3-none-any.whl (179 kB)\n",
      "  Using cached google_cloud_bigquery_storage-2.11.0-py2.py3-none-any.whl (172 kB)\n",
      "Collecting libcst>=0.2.5 (from google-cloud-bigquery-storage<3,>=2.6.3->apache-beam[gcp]<3,>=2.47->tfx)\n",
      "  Obtaining dependency information for libcst>=0.2.5 from https://files.pythonhosted.org/packages/2a/bc/1112e0707566230709965817f2881fc18f9a322bbbb52ae8adf7c28981cc/libcst-1.0.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata\n",
      "  Using cached libcst-1.0.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (17 kB)\n",
      "Collecting google-cloud-bigquery-storage<3,>=2.6.3 (from apache-beam[gcp]<3,>=2.47->tfx)\n",
      "  Using cached google_cloud_bigquery_storage-2.10.1-py2.py3-none-any.whl (171 kB)\n",
      "  Using cached google_cloud_bigquery_storage-2.10.0-py2.py3-none-any.whl (171 kB)\n",
      "  Using cached google_cloud_bigquery_storage-2.9.1-py2.py3-none-any.whl (170 kB)\n",
      "  Using cached google_cloud_bigquery_storage-2.9.0-py2.py3-none-any.whl (170 kB)\n",
      "  Using cached google_cloud_bigquery_storage-2.8.0-py2.py3-none-any.whl (131 kB)\n",
      "  Using cached google_cloud_bigquery_storage-2.7.0-py2.py3-none-any.whl (125 kB)\n",
      "  Using cached google_cloud_bigquery_storage-2.6.3-py2.py3-none-any.whl (125 kB)\n",
      "Collecting google-cloud-bigquery<3,>=2.26.0 (from tfx)\n",
      "  Using cached google_cloud_bigquery-2.34.3-py2.py3-none-any.whl (206 kB)\n",
      "  Using cached google_cloud_bigquery-2.34.2-py2.py3-none-any.whl (206 kB)\n",
      "  Using cached google_cloud_bigquery-2.34.1-py2.py3-none-any.whl (206 kB)\n",
      "  Using cached google_cloud_bigquery-2.34.0-py2.py3-none-any.whl (206 kB)\n",
      "  Using cached google_cloud_bigquery-2.33.0-py2.py3-none-any.whl (205 kB)\n",
      "  Using cached google_cloud_bigquery-2.32.0-py2.py3-none-any.whl (205 kB)\n",
      "  Using cached google_cloud_bigquery-2.31.0-py2.py3-none-any.whl (205 kB)\n",
      "  Using cached google_cloud_bigquery-2.30.1-py2.py3-none-any.whl (203 kB)\n",
      "  Using cached google_cloud_bigquery-2.30.0-py2.py3-none-any.whl (203 kB)\n",
      "  Using cached google_cloud_bigquery-2.29.0-py2.py3-none-any.whl (203 kB)\n",
      "  Using cached google_cloud_bigquery-2.28.1-py2.py3-none-any.whl (202 kB)\n",
      "  Using cached google_cloud_bigquery-2.28.0-py2.py3-none-any.whl (202 kB)\n",
      "  Using cached google_cloud_bigquery-2.27.1-py2.py3-none-any.whl (201 kB)\n",
      "  Using cached google_cloud_bigquery-2.27.0-py2.py3-none-any.whl (201 kB)\n",
      "  Using cached google_cloud_bigquery-2.26.0-py2.py3-none-any.whl (201 kB)\n",
      "Collecting google-cloud-aiplatform<2,>=1.6.2 (from tfx)\n",
      "  Obtaining dependency information for google-cloud-aiplatform<2,>=1.6.2 from https://files.pythonhosted.org/packages/04/13/67cfb50656122f8f2c5d0b5548a1a08feaeff650174348f353c5adc8230e/google_cloud_aiplatform-1.33.0-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_cloud_aiplatform-1.33.0-py2.py3-none-any.whl.metadata (27 kB)\n",
      "  Obtaining dependency information for google-cloud-aiplatform<2,>=1.6.2 from https://files.pythonhosted.org/packages/33/8a/e0bb96ad439a3cc11671a4f5fb1ff2f0d3a9993e325d82859ba75cfebd77/google_cloud_aiplatform-1.32.0-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_cloud_aiplatform-1.32.0-py2.py3-none-any.whl.metadata (25 kB)\n",
      "  Obtaining dependency information for google-cloud-aiplatform<2,>=1.6.2 from https://files.pythonhosted.org/packages/0b/7c/fcbb346dbfe4de0b4cccf33ed114b94921a970f7624a8b42c1aa54b7699d/google_cloud_aiplatform-1.31.1-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_cloud_aiplatform-1.31.1-py2.py3-none-any.whl.metadata (25 kB)\n",
      "  Obtaining dependency information for google-cloud-aiplatform<2,>=1.6.2 from https://files.pythonhosted.org/packages/5e/c9/bc727aa6d015128a728eb9fda4378b5493f5131c92b7e970bbf5f4c3eba8/google_cloud_aiplatform-1.31.0-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_cloud_aiplatform-1.31.0-py2.py3-none-any.whl.metadata (25 kB)\n",
      "  Obtaining dependency information for google-cloud-aiplatform<2,>=1.6.2 from https://files.pythonhosted.org/packages/a6/bf/e5ce3e5ddd150f92ec4bda3387706ccc4a6f10d71a26e542174ea7090f77/google_cloud_aiplatform-1.30.1-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_cloud_aiplatform-1.30.1-py2.py3-none-any.whl.metadata (24 kB)\n",
      "  Obtaining dependency information for google-cloud-aiplatform<2,>=1.6.2 from https://files.pythonhosted.org/packages/ab/fd/d1f5df6f53355b37886792fc88d4626827b1acf12ce3376653d6939a4d12/google_cloud_aiplatform-1.30.0-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_cloud_aiplatform-1.30.0-py2.py3-none-any.whl.metadata (24 kB)\n",
      "  Obtaining dependency information for google-cloud-aiplatform<2,>=1.6.2 from https://files.pythonhosted.org/packages/d3/0c/a842571cb82ae7cb56a0af3b2b2ab3b35baa113c4adf346022a5ea8bcff0/google_cloud_aiplatform-1.29.0-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_cloud_aiplatform-1.29.0-py2.py3-none-any.whl.metadata (24 kB)\n",
      "  Obtaining dependency information for google-cloud-aiplatform<2,>=1.6.2 from https://files.pythonhosted.org/packages/8f/3f/979e65dc13c11b4c53241d105d41d4b937b131e56b68397cc279f372be96/google_cloud_aiplatform-1.28.1-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_cloud_aiplatform-1.28.1-py2.py3-none-any.whl.metadata (24 kB)\n",
      "  Obtaining dependency information for google-cloud-aiplatform<2,>=1.6.2 from https://files.pythonhosted.org/packages/4e/d4/177f074f42b0d1d575e075e718d3fec8f0563d2a1cd6b5e5de951a6fdf86/google_cloud_aiplatform-1.28.0-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_cloud_aiplatform-1.28.0-py2.py3-none-any.whl.metadata (24 kB)\n",
      "  Obtaining dependency information for google-cloud-aiplatform<2,>=1.6.2 from https://files.pythonhosted.org/packages/15/86/29705df54b1ee3ea7585d793482ee54bb0bbcbab72bc1734c87809335f9f/google_cloud_aiplatform-1.27.1-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_cloud_aiplatform-1.27.1-py2.py3-none-any.whl.metadata (24 kB)\n",
      "  Obtaining dependency information for google-cloud-aiplatform<2,>=1.6.2 from https://files.pythonhosted.org/packages/1f/59/98ced5e47bdd9306d14111f1a309ec6f4c2fe9b0e30f70c8a12d3f31405f/google_cloud_aiplatform-1.27.0-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_cloud_aiplatform-1.27.0-py2.py3-none-any.whl.metadata (24 kB)\n",
      "  Obtaining dependency information for google-cloud-aiplatform<2,>=1.6.2 from https://files.pythonhosted.org/packages/63/bc/5f598c90a482c1bca4952e76ceb06d23ff4a64ab75f7bf0013e2eeee1231/google_cloud_aiplatform-1.26.1-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_cloud_aiplatform-1.26.1-py2.py3-none-any.whl.metadata (24 kB)\n",
      "  Obtaining dependency information for google-cloud-aiplatform<2,>=1.6.2 from https://files.pythonhosted.org/packages/53/c6/a740451148b41f38eb9c6a948a17e69febcbcf7b2f5671acfbcd26c54f10/google_cloud_aiplatform-1.26.0-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_cloud_aiplatform-1.26.0-py2.py3-none-any.whl.metadata (24 kB)\n",
      "Collecting apache-beam[gcp]<3,>=2.47 (from tfx)\n",
      "  Obtaining dependency information for apache-beam[gcp]<3,>=2.47 from https://files.pythonhosted.org/packages/c0/a6/ef1ca30b8b1b71a1684349f810180aab5411ed582900d8fb1d6c3fd83fe4/apache_beam-2.49.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata\n",
      "  Using cached apache_beam-2.49.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.9 kB)\n",
      "  Obtaining dependency information for apache-beam[gcp]<3,>=2.47 from https://files.pythonhosted.org/packages/9d/1b/59d9717241170b707fbdd82fa74a676260e7fa03fecfa7fafd58f0c178e1/apache_beam-2.48.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata\n",
      "  Using cached apache_beam-2.48.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.2 kB)\n",
      "Collecting google-cloud-bigtable<2.18.0,>=2.0.0 (from apache-beam[gcp]<3,>=2.47->tfx)\n",
      "  Using cached google_cloud_bigtable-2.17.0-py2.py3-none-any.whl (288 kB)\n",
      "  Using cached google_cloud_bigtable-2.16.0-py2.py3-none-any.whl (288 kB)\n",
      "  Using cached google_cloud_bigtable-2.15.0-py2.py3-none-any.whl (252 kB)\n",
      "Collecting grpc-google-iam-v1<1.0.0dev,>=0.12.4 (from google-cloud-bigtable<2.18.0,>=2.0.0->apache-beam[gcp]<3,>=2.47->tfx)\n",
      "  Using cached grpc_google_iam_v1-0.12.6-py2.py3-none-any.whl (26 kB)\n",
      "INFO: pip is looking at multiple versions of google-cloud-datastore to determine which version is compatible with other requirements. This could take a while.\n",
      "Collecting google-cloud-datastore<3,>=2.0.0 (from apache-beam[gcp]<3,>=2.47->tfx)\n",
      "  Obtaining dependency information for google-cloud-datastore<3,>=2.0.0 from https://files.pythonhosted.org/packages/45/44/e2ee842931fe00d8e7506dcb3206afaa8d32a661e04f09d01931f6f4003f/google_cloud_datastore-2.17.0-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_cloud_datastore-2.17.0-py2.py3-none-any.whl.metadata (5.5 kB)\n",
      "  Obtaining dependency information for google-cloud-datastore<3,>=2.0.0 from https://files.pythonhosted.org/packages/c4/10/1281beff5567742559bfd447719fa61037b1b4e52ac644497aa16e8196ce/google_cloud_datastore-2.16.1-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_cloud_datastore-2.16.1-py2.py3-none-any.whl.metadata (5.4 kB)\n",
      "  Obtaining dependency information for google-cloud-datastore<3,>=2.0.0 from https://files.pythonhosted.org/packages/95/80/10b6759ce4c5b93887baf92d65995854996403c331e3db7ca68c87059233/google_cloud_datastore-2.16.0-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_cloud_datastore-2.16.0-py2.py3-none-any.whl.metadata (5.4 kB)\n",
      "  Using cached google_cloud_datastore-2.15.2-py2.py3-none-any.whl (175 kB)\n",
      "  Using cached google_cloud_datastore-2.15.1-py2.py3-none-any.whl (175 kB)\n",
      "  Using cached google_cloud_datastore-2.15.0-py2.py3-none-any.whl (175 kB)\n",
      "  Using cached google_cloud_datastore-2.14.0-py2.py3-none-any.whl (174 kB)\n",
      "INFO: pip is still looking at multiple versions of google-cloud-datastore to determine which version is compatible with other requirements. This could take a while.\n",
      "  Using cached google_cloud_datastore-2.13.2-py2.py3-none-any.whl (158 kB)\n",
      "  Using cached google_cloud_datastore-2.13.1-py2.py3-none-any.whl (158 kB)\n",
      "  Using cached google_cloud_datastore-2.13.0-py2.py3-none-any.whl (156 kB)\n",
      "  Using cached google_cloud_datastore-2.12.0-py2.py3-none-any.whl (156 kB)\n",
      "  Using cached google_cloud_datastore-2.11.1-py2.py3-none-any.whl (156 kB)\n",
      "INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.\n",
      "  Using cached google_cloud_datastore-2.11.0-py2.py3-none-any.whl (155 kB)\n",
      "INFO: pip is looking at multiple versions of google-cloud-dlp to determine which version is compatible with other requirements. This could take a while.\n",
      "Collecting google-cloud-dlp<4,>=3.0.0 (from apache-beam[gcp]<3,>=2.47->tfx)\n",
      "  Obtaining dependency information for google-cloud-dlp<4,>=3.0.0 from https://files.pythonhosted.org/packages/83/21/1d12ac0200d599ac7d2d9ec735851fa51eb365b962638de124247645232f/google_cloud_dlp-3.12.2-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_cloud_dlp-3.12.2-py2.py3-none-any.whl.metadata (5.1 kB)\n",
      "  Using cached google_cloud_dlp-3.12.1-py2.py3-none-any.whl (143 kB)\n",
      "  Using cached google_cloud_dlp-3.12.0-py2.py3-none-any.whl (143 kB)\n",
      "  Using cached google_cloud_dlp-3.11.1-py2.py3-none-any.whl (131 kB)\n",
      "  Using cached google_cloud_dlp-3.11.0-py2.py3-none-any.whl (126 kB)\n",
      "  Using cached google_cloud_dlp-3.10.1-py2.py3-none-any.whl (125 kB)\n",
      "  Using cached google_cloud_dlp-3.10.0-py2.py3-none-any.whl (125 kB)\n",
      "INFO: pip is still looking at multiple versions of google-cloud-dlp to determine which version is compatible with other requirements. This could take a while.\n",
      "  Using cached google_cloud_dlp-3.9.2-py2.py3-none-any.whl (125 kB)\n",
      "INFO: pip is looking at multiple versions of google-cloud-language to determine which version is compatible with other requirements. This could take a while.\n",
      "Collecting google-cloud-language<3,>=2.0 (from apache-beam[gcp]<3,>=2.47->tfx)\n",
      "  Obtaining dependency information for google-cloud-language<3,>=2.0 from https://files.pythonhosted.org/packages/0b/28/a137e4b56fd79595b42a5e14576148337265d8218d0787068610a004158b/google_cloud_language-2.11.0-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_cloud_language-2.11.0-py2.py3-none-any.whl.metadata (5.3 kB)\n",
      "  Obtaining dependency information for google-cloud-language<3,>=2.0 from https://files.pythonhosted.org/packages/a1/b5/87c4a778b72abe92035a6ed5e4fa845723ece716969f1c08c85824be1206/google_cloud_language-2.10.1-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_cloud_language-2.10.1-py2.py3-none-any.whl.metadata (5.2 kB)\n",
      "  Obtaining dependency information for google-cloud-language<3,>=2.0 from https://files.pythonhosted.org/packages/bc/bd/1e433d527463064971aeb8015dacb3ee4265c4b5d8032bb71d6f238921f3/google_cloud_language-2.10.0-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_cloud_language-2.10.0-py2.py3-none-any.whl.metadata (5.2 kB)\n",
      "  Using cached google_cloud_language-2.9.1-py2.py3-none-any.whl (99 kB)\n",
      "  Using cached google_cloud_language-2.9.0-py2.py3-none-any.whl (99 kB)\n",
      "  Using cached google_cloud_language-2.8.1-py2.py3-none-any.whl (88 kB)\n",
      "  Using cached google_cloud_language-2.8.0-py2.py3-none-any.whl (81 kB)\n",
      "INFO: pip is still looking at multiple versions of google-cloud-language to determine which version is compatible with other requirements. This could take a while.\n",
      "  Using cached google_cloud_language-2.7.0-py2.py3-none-any.whl (81 kB)\n",
      "  Using cached google_cloud_language-2.6.1-py2.py3-none-any.whl (84 kB)\n",
      "INFO: pip is looking at multiple versions of google-cloud-pubsub to determine which version is compatible with other requirements. This could take a while.\n",
      "Collecting google-cloud-pubsub<3,>=2.1.0 (from apache-beam[gcp]<3,>=2.47->tfx)\n",
      "  Obtaining dependency information for google-cloud-pubsub<3,>=2.1.0 from https://files.pythonhosted.org/packages/e2/00/916d3934aeb1c602f4a0e2b658d844dd47264cd7e53851f60f334c095608/google_cloud_pubsub-2.18.3-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_cloud_pubsub-2.18.3-py2.py3-none-any.whl.metadata (9.2 kB)\n",
      "  Obtaining dependency information for google-cloud-pubsub<3,>=2.1.0 from https://files.pythonhosted.org/packages/a2/50/3c2993f929985a4fca742ff776878e4f4d3e804b8efd345fdfd054a46e6b/google_cloud_pubsub-2.18.2-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_cloud_pubsub-2.18.2-py2.py3-none-any.whl.metadata (9.2 kB)\n",
      "  Obtaining dependency information for google-cloud-pubsub<3,>=2.1.0 from https://files.pythonhosted.org/packages/be/60/22d3609eb807514c91b291b7075243a9b5924d1f3a557325ccd7de15f32b/google_cloud_pubsub-2.18.1-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_cloud_pubsub-2.18.1-py2.py3-none-any.whl.metadata (9.2 kB)\n",
      "  Obtaining dependency information for google-cloud-pubsub<3,>=2.1.0 from https://files.pythonhosted.org/packages/51/8d/3784f023a00c0d0fa0860d131039df6ce58b3f10abbb84f91f7d4c0f13a3/google_cloud_pubsub-2.18.0-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_cloud_pubsub-2.18.0-py2.py3-none-any.whl.metadata (9.2 kB)\n",
      "  Obtaining dependency information for google-cloud-pubsub<3,>=2.1.0 from https://files.pythonhosted.org/packages/f5/21/1a70e8d2959d578e8365241af7a6cf463d6f0ee56ae7f7d4ba4a4914a4fe/google_cloud_pubsub-2.17.1-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_cloud_pubsub-2.17.1-py2.py3-none-any.whl.metadata (9.4 kB)\n",
      "  Obtaining dependency information for google-cloud-pubsub<3,>=2.1.0 from https://files.pythonhosted.org/packages/c8/98/54e08d32d9990754f66a8625a3d4ba7a8152451c4dc682ca969ac49eaf0b/google_cloud_pubsub-2.17.0-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_cloud_pubsub-2.17.0-py2.py3-none-any.whl.metadata (9.4 kB)\n",
      "  Using cached google_cloud_pubsub-2.16.1-py2.py3-none-any.whl (263 kB)\n",
      "INFO: pip is still looking at multiple versions of google-cloud-pubsub to determine which version is compatible with other requirements. This could take a while.\n",
      "  Using cached google_cloud_pubsub-2.16.0-py2.py3-none-any.whl (263 kB)\n",
      "  Using cached google_cloud_pubsub-2.15.2-py2.py3-none-any.whl (243 kB)\n",
      "  Using cached google_cloud_pubsub-2.15.1-py2.py3-none-any.whl (243 kB)\n",
      "  Using cached google_cloud_pubsub-2.15.0-py2.py3-none-any.whl (242 kB)\n",
      "  Using cached google_cloud_pubsub-2.14.1-py2.py3-none-any.whl (242 kB)\n",
      "INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.\n",
      "  Using cached google_cloud_pubsub-2.14.0-py2.py3-none-any.whl (241 kB)\n",
      "  Using cached google_cloud_pubsub-2.13.12-py2.py3-none-any.whl (238 kB)\n",
      "  Using cached google_cloud_pubsub-2.13.11-py2.py3-none-any.whl (236 kB)\n",
      "Collecting overrides<7.0.0,>=6.0.1 (from google-cloud-pubsublite<2,>=1.2.0->apache-beam[gcp]<3,>=2.47->tfx)\n",
      "  Using cached overrides-6.5.0-py3-none-any.whl (17 kB)\n",
      "INFO: pip is looking at multiple versions of google-cloud-recommendations-ai to determine which version is compatible with other requirements. This could take a while.\n",
      "Collecting google-cloud-recommendations-ai<0.11.0,>=0.1.0 (from apache-beam[gcp]<3,>=2.47->tfx)\n",
      "  Obtaining dependency information for google-cloud-recommendations-ai<0.11.0,>=0.1.0 from https://files.pythonhosted.org/packages/84/c9/14998f5e22c536e06cf452549c6cdfca1c521fe931751d90890c1eb15653/google_cloud_recommendations_ai-0.10.4-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_cloud_recommendations_ai-0.10.4-py2.py3-none-any.whl.metadata (5.1 kB)\n",
      "  Using cached google_cloud_recommendations_ai-0.10.3-py2.py3-none-any.whl (173 kB)\n",
      "  Using cached google_cloud_recommendations_ai-0.10.2-py2.py3-none-any.whl (173 kB)\n",
      "  Using cached google_cloud_recommendations_ai-0.10.1-py2.py3-none-any.whl (173 kB)\n",
      "  Using cached google_cloud_recommendations_ai-0.10.0-py2.py3-none-any.whl (172 kB)\n",
      "  Using cached google_cloud_recommendations_ai-0.9.0-py2.py3-none-any.whl (172 kB)\n",
      "  Using cached google_cloud_recommendations_ai-0.8.2-py2.py3-none-any.whl (171 kB)\n",
      "INFO: pip is looking at multiple versions of google-cloud-resource-manager to determine which version is compatible with other requirements. This could take a while.\n",
      "Collecting google-cloud-resource-manager<3.0.0dev,>=1.3.3 (from google-cloud-aiplatform<2,>=1.6.2->tfx)\n",
      "  Obtaining dependency information for google-cloud-resource-manager<3.0.0dev,>=1.3.3 from https://files.pythonhosted.org/packages/d2/f3/e7d1848edf2f4714d8925e6c749464c190e696b3c85264441c2b3787ae72/google_cloud_resource_manager-1.10.3-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_cloud_resource_manager-1.10.3-py2.py3-none-any.whl.metadata (5.2 kB)\n",
      "  Obtaining dependency information for google-cloud-resource-manager<3.0.0dev,>=1.3.3 from https://files.pythonhosted.org/packages/cb/88/4fc0d6be354fbf74e8192937ef58661fce38bbf188450f952da97f3ebb47/google_cloud_resource_manager-1.10.2-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_cloud_resource_manager-1.10.2-py2.py3-none-any.whl.metadata (5.1 kB)\n",
      "  Obtaining dependency information for google-cloud-resource-manager<3.0.0dev,>=1.3.3 from https://files.pythonhosted.org/packages/18/e8/600cdd5321e6f76c86162aee083756b4b5f77cf0894dc9de059aca4656bd/google_cloud_resource_manager-1.10.1-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_cloud_resource_manager-1.10.1-py2.py3-none-any.whl.metadata (5.2 kB)\n",
      "  Using cached google_cloud_resource_manager-1.10.0-py2.py3-none-any.whl (321 kB)\n",
      "  Using cached google_cloud_resource_manager-1.9.1-py2.py3-none-any.whl (276 kB)\n",
      "  Using cached google_cloud_resource_manager-1.9.0-py2.py3-none-any.whl (276 kB)\n",
      "  Using cached google_cloud_resource_manager-1.8.1-py2.py3-none-any.whl (235 kB)\n",
      "INFO: pip is still looking at multiple versions of google-cloud-resource-manager to determine which version is compatible with other requirements. This could take a while.\n",
      "  Using cached google_cloud_resource_manager-1.8.0-py2.py3-none-any.whl (235 kB)\n",
      "  Using cached google_cloud_resource_manager-1.7.0-py2.py3-none-any.whl (235 kB)\n",
      "  Using cached google_cloud_resource_manager-1.6.3-py2.py3-none-any.whl (233 kB)\n",
      "INFO: pip is looking at multiple versions of google-cloud-spanner to determine which version is compatible with other requirements. This could take a while.\n",
      "Collecting google-cloud-spanner<4,>=3.0.0 (from apache-beam[gcp]<3,>=2.47->tfx)\n",
      "  Obtaining dependency information for google-cloud-spanner<4,>=3.0.0 from https://files.pythonhosted.org/packages/e9/a8/31e93da06b9da3e6d5729f8fa5f7c21a47cfd1c19ec7a6f3a9587a19901e/google_cloud_spanner-3.40.0-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_cloud_spanner-3.40.0-py2.py3-none-any.whl.metadata (10 kB)\n",
      "  Obtaining dependency information for google-cloud-spanner<4,>=3.0.0 from https://files.pythonhosted.org/packages/a4/80/a09c81dc83a7906a5ec33af55ffbf91aabdd923f7b06528b2a5985e3ae38/google_cloud_spanner-3.39.0-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_cloud_spanner-3.39.0-py2.py3-none-any.whl.metadata (10 kB)\n",
      "  Obtaining dependency information for google-cloud-spanner<4,>=3.0.0 from https://files.pythonhosted.org/packages/5e/5c/7b69a80efeb9106612d15c6fa0338ea2a0806b6f2178fef19bd0e069b630/google_cloud_spanner-3.38.0-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_cloud_spanner-3.38.0-py2.py3-none-any.whl.metadata (10 kB)\n",
      "  Obtaining dependency information for google-cloud-spanner<4,>=3.0.0 from https://files.pythonhosted.org/packages/32/bc/ba4eddcb589f7633bb43cab477fdf8b4460778128286e143d6cbb05c4da0/google_cloud_spanner-3.37.0-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_cloud_spanner-3.37.0-py2.py3-none-any.whl.metadata (10 kB)\n",
      "  Obtaining dependency information for google-cloud-spanner<4,>=3.0.0 from https://files.pythonhosted.org/packages/d9/54/aabeec25d96edfc3448da88adfd0012397bf7e11308bc3862dcdad1ef133/google_cloud_spanner-3.36.0-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_cloud_spanner-3.36.0-py2.py3-none-any.whl.metadata (10 kB)\n",
      "  Obtaining dependency information for google-cloud-spanner<4,>=3.0.0 from https://files.pythonhosted.org/packages/a2/9f/5a4176995bfbc81c6fd887077c2cf5de2d4afa5996641e075b54f83e1a94/google_cloud_spanner-3.35.1-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_cloud_spanner-3.35.1-py2.py3-none-any.whl.metadata (10 kB)\n",
      "  Obtaining dependency information for google-cloud-spanner<4,>=3.0.0 from https://files.pythonhosted.org/packages/ab/82/e3b60154b9ced9318882d9bdf10a1121457b1007d9603da5d1a4ba4ca9d9/google_cloud_spanner-3.35.0-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_cloud_spanner-3.35.0-py2.py3-none-any.whl.metadata (10 kB)\n",
      "INFO: pip is still looking at multiple versions of google-cloud-spanner to determine which version is compatible with other requirements. This could take a while.\n",
      "  Obtaining dependency information for google-cloud-spanner<4,>=3.0.0 from https://files.pythonhosted.org/packages/e8/bc/d46d1d4e386f8b55d9c03aad28c8452b4a49484ebd2cd4d92e6cf373e1d1/google_cloud_spanner-3.34.0-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_cloud_spanner-3.34.0-py2.py3-none-any.whl.metadata (10 kB)\n",
      "  Using cached google_cloud_spanner-3.33.0-py2.py3-none-any.whl (328 kB)\n",
      "  Using cached google_cloud_spanner-3.32.0-py2.py3-none-any.whl (327 kB)\n",
      "  Using cached google_cloud_spanner-3.31.0-py2.py3-none-any.whl (327 kB)\n",
      "  Using cached google_cloud_spanner-3.30.0-py2.py3-none-any.whl (327 kB)\n",
      "INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.\n",
      "  Using cached google_cloud_spanner-3.29.0-py2.py3-none-any.whl (327 kB)\n",
      "  Using cached google_cloud_spanner-3.28.0-py2.py3-none-any.whl (327 kB)\n",
      "  Using cached google_cloud_spanner-3.27.1-py2.py3-none-any.whl (300 kB)\n",
      "  Using cached google_cloud_spanner-3.27.0-py2.py3-none-any.whl (297 kB)\n",
      "  Using cached google_cloud_spanner-3.26.0-py2.py3-none-any.whl (294 kB)\n",
      "Requirement already satisfied: sqlparse>=0.3.0 in /opt/conda/lib/python3.8/site-packages (from google-cloud-spanner<4,>=3.0.0->apache-beam[gcp]<3,>=2.47->tfx) (0.4.4)\n",
      "INFO: pip is looking at multiple versions of google-cloud-videointelligence to determine which version is compatible with other requirements. This could take a while.\n",
      "Collecting google-cloud-videointelligence<3,>=2.0 (from apache-beam[gcp]<3,>=2.47->tfx)\n",
      "  Obtaining dependency information for google-cloud-videointelligence<3,>=2.0 from https://files.pythonhosted.org/packages/54/49/463abf7c16f703d40951c21e9d9439702923127ae5acad2c4924dbc52288/google_cloud_videointelligence-2.11.3-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_cloud_videointelligence-2.11.3-py2.py3-none-any.whl.metadata (5.5 kB)\n",
      "  Obtaining dependency information for google-cloud-videointelligence<3,>=2.0 from https://files.pythonhosted.org/packages/96/a1/6128fe5ed6bc4faf1ca1d4416b7c116ee566496d220e9af9c4d523388977/google_cloud_videointelligence-2.11.2-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_cloud_videointelligence-2.11.2-py2.py3-none-any.whl.metadata (5.5 kB)\n",
      "  Using cached google_cloud_videointelligence-2.11.1-py2.py3-none-any.whl (229 kB)\n",
      "  Using cached google_cloud_videointelligence-2.11.0-py2.py3-none-any.whl (229 kB)\n",
      "  Using cached google_cloud_videointelligence-2.10.1-py2.py3-none-any.whl (210 kB)\n",
      "  Using cached google_cloud_videointelligence-2.10.0-py2.py3-none-any.whl (208 kB)\n",
      "  Using cached google_cloud_videointelligence-2.9.0-py2.py3-none-any.whl (208 kB)\n",
      "INFO: pip is still looking at multiple versions of google-cloud-videointelligence to determine which version is compatible with other requirements. This could take a while.\n",
      "  Using cached google_cloud_videointelligence-2.8.3-py2.py3-none-any.whl (206 kB)\n",
      "INFO: pip is looking at multiple versions of google-cloud-vision to determine which version is compatible with other requirements. This could take a while.\n",
      "Collecting google-cloud-vision<4,>=2 (from apache-beam[gcp]<3,>=2.47->tfx)\n",
      "  Obtaining dependency information for google-cloud-vision<4,>=2 from https://files.pythonhosted.org/packages/39/13/c7c28209b32909cc261634c62273373c3db82a1a06accba3730fae9a0757/google_cloud_vision-3.4.3-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_cloud_vision-3.4.3-py2.py3-none-any.whl.metadata (6.2 kB)\n",
      "  Obtaining dependency information for google-cloud-vision<4,>=2 from https://files.pythonhosted.org/packages/24/bf/14e72eb9b247f354ee5278112173ed1b05f228ae4072f081830c5fd4f597/google_cloud_vision-3.4.2-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_cloud_vision-3.4.2-py2.py3-none-any.whl.metadata (6.3 kB)\n",
      "  Using cached google_cloud_vision-3.4.1-py2.py3-none-any.whl (444 kB)\n",
      "  Using cached google_cloud_vision-3.4.0-py2.py3-none-any.whl (444 kB)\n",
      "  Using cached google_cloud_vision-3.3.1-py2.py3-none-any.whl (393 kB)\n",
      "  Using cached google_cloud_vision-3.3.0-py2.py3-none-any.whl (386 kB)\n",
      "  Using cached google_cloud_vision-3.2.0-py2.py3-none-any.whl (386 kB)\n",
      "INFO: pip is still looking at multiple versions of google-cloud-vision to determine which version is compatible with other requirements. This could take a while.\n",
      "  Using cached google_cloud_vision-3.1.4-py2.py3-none-any.whl (390 kB)\n",
      "Requirement already satisfied: google-crc32c<2.0dev,>=1.0 in /opt/conda/lib/python3.8/site-packages (from google-resumable-media<3.0dev,>=0.6.0->google-cloud-bigquery<3,>=2.26.0->tfx) (1.5.0)\n",
      "Collecting docopt (from hdfs<3.0.0,>=2.1.0->apache-beam[gcp]<3,>=2.47->tfx)\n",
      "  Using cached docopt-0.6.2-py2.py3-none-any.whl\n",
      "Requirement already satisfied: jedi>=0.16 in /opt/conda/lib/python3.8/site-packages (from ipython<8,>=7->tensorflow-model-analysis<0.46.0,>=0.45.0->tfx) (0.18.2)\n",
      "Requirement already satisfied: decorator in /opt/conda/lib/python3.8/site-packages (from ipython<8,>=7->tensorflow-model-analysis<0.46.0,>=0.45.0->tfx) (5.1.1)\n",
      "Requirement already satisfied: pickleshare in /opt/conda/lib/python3.8/site-packages (from ipython<8,>=7->tensorflow-model-analysis<0.46.0,>=0.45.0->tfx) (0.7.5)\n",
      "Requirement already satisfied: traitlets>=4.2 in /opt/conda/lib/python3.8/site-packages (from ipython<8,>=7->tensorflow-model-analysis<0.46.0,>=0.45.0->tfx) (5.9.0)\n",
      "Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /opt/conda/lib/python3.8/site-packages (from ipython<8,>=7->tensorflow-model-analysis<0.46.0,>=0.45.0->tfx) (3.0.38)\n",
      "Requirement already satisfied: pygments in /opt/conda/lib/python3.8/site-packages (from ipython<8,>=7->tensorflow-model-analysis<0.46.0,>=0.45.0->tfx) (2.15.1)\n",
      "Requirement already satisfied: backcall in /opt/conda/lib/python3.8/site-packages (from ipython<8,>=7->tensorflow-model-analysis<0.46.0,>=0.45.0->tfx) (0.2.0)\n",
      "Requirement already satisfied: matplotlib-inline in /opt/conda/lib/python3.8/site-packages (from ipython<8,>=7->tensorflow-model-analysis<0.46.0,>=0.45.0->tfx) (0.1.6)\n",
      "Requirement already satisfied: pexpect>4.3 in /opt/conda/lib/python3.8/site-packages (from ipython<8,>=7->tensorflow-model-analysis<0.46.0,>=0.45.0->tfx) (4.8.0)\n",
      "Requirement already satisfied: ipykernel>=4.5.1 in /opt/conda/lib/python3.8/site-packages (from ipywidgets<8,>=7->tensorflow-model-analysis<0.46.0,>=0.45.0->tfx) (6.15.0)\n",
      "Requirement already satisfied: nbformat>=4.2.0 in /opt/conda/lib/python3.8/site-packages (from ipywidgets<8,>=7->tensorflow-model-analysis<0.46.0,>=0.45.0->tfx) (5.7.3)\n",
      "Requirement already satisfied: widgetsnbextension~=3.5.0 in /opt/conda/lib/python3.8/site-packages (from ipywidgets<8,>=7->tensorflow-model-analysis<0.46.0,>=0.45.0->tfx) (3.5.2)\n",
      "Requirement already satisfied: jupyterlab-widgets>=1.0.0 in /opt/conda/lib/python3.8/site-packages (from ipywidgets<8,>=7->tensorflow-model-analysis<0.46.0,>=0.45.0->tfx) (3.0.7)\n",
      "Requirement already satisfied: pyasn1>=0.1.7 in /opt/conda/lib/python3.8/site-packages (from oauth2client>=1.4.12->google-apitools<1,>=0.5->tfx) (0.5.0)\n",
      "Collecting dnspython<3.0.0,>=1.16.0 (from pymongo<5.0.0,>=3.8.0->apache-beam[gcp]<3,>=2.47->tfx)\n",
      "  Obtaining dependency information for dnspython<3.0.0,>=1.16.0 from https://files.pythonhosted.org/packages/f6/b4/0a9bee52c50f226a3cbfb54263d02bb421c7f2adc136520729c2c689c1e5/dnspython-2.4.2-py3-none-any.whl.metadata\n",
      "  Using cached dnspython-2.4.2-py3-none-any.whl.metadata (4.9 kB)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in /opt/conda/lib/python3.8/site-packages (from requests<3.0.0,>=2.24.0->apache-beam[gcp]<3,>=2.47->tfx) (3.1.0)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.8/site-packages (from requests<3.0.0,>=2.24.0->apache-beam[gcp]<3,>=2.47->tfx) (3.4)\n",
      "Requirement already satisfied: google-auth-oauthlib<1.1,>=0.5 in /opt/conda/lib/python3.8/site-packages (from tensorboard<2.14,>=2.13->tensorflow<2.14,>=2.13.0->tfx) (1.0.0)\n",
      "Requirement already satisfied: markdown>=2.6.8 in /opt/conda/lib/python3.8/site-packages (from tensorboard<2.14,>=2.13->tensorflow<2.14,>=2.13.0->tfx) (3.4.3)\n",
      "Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /opt/conda/lib/python3.8/site-packages (from tensorboard<2.14,>=2.13->tensorflow<2.14,>=2.13.0->tfx) (0.7.0)\n",
      "Requirement already satisfied: werkzeug>=1.0.1 in /opt/conda/lib/python3.8/site-packages (from tensorboard<2.14,>=2.13->tensorflow<2.14,>=2.13.0->tfx) (2.2.3)\n",
      "Collecting rich (from keras-core->keras-tuner<2,>=1.0.4->tfx)\n",
      "  Obtaining dependency information for rich from https://files.pythonhosted.org/packages/c1/d1/23ba6235ed82883bb416f57179d1db2c05f3fb8e5d83c18660f9ab6f09c9/rich-13.5.3-py3-none-any.whl.metadata\n",
      "  Using cached rich-13.5.3-py3-none-any.whl.metadata (18 kB)\n",
      "Collecting namex (from keras-core->keras-tuner<2,>=1.0.4->tfx)\n",
      "  Using cached namex-0.0.7-py3-none-any.whl (5.8 kB)\n",
      "Collecting dm-tree (from keras-core->keras-tuner<2,>=1.0.4->tfx)\n",
      "  Using cached dm_tree-0.1.8-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (152 kB)\n",
      "Requirement already satisfied: oauthlib>=3.0.0 in /opt/conda/lib/python3.8/site-packages (from requests-oauthlib->kubernetes<13,>=10.0.1->tfx) (3.2.2)\n",
      "Collecting google-auth<3.0dev,>=1.25.0 (from google-api-core<3->tfx)\n",
      "  Obtaining dependency information for google-auth<3.0dev,>=1.25.0 from https://files.pythonhosted.org/packages/23/e4/abbb8763fdf6279c471443251b3f847ee9a172d1776742b266fe6de7ac86/google_auth-2.23.1-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_auth-2.23.1-py2.py3-none-any.whl.metadata (4.2 kB)\n",
      "INFO: pip is looking at multiple versions of google-auth to determine which version is compatible with other requirements. This could take a while.\n",
      "  Obtaining dependency information for google-auth<3.0dev,>=1.25.0 from https://files.pythonhosted.org/packages/9d/44/5a992cb9d7bf8aaae73bc5adaf721ad08731c9d00c1c17999a8691404b0c/google_auth-2.23.0-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_auth-2.23.0-py2.py3-none-any.whl.metadata (4.2 kB)\n",
      "INFO: pip is looking at multiple versions of grpcio-status to determine which version is compatible with other requirements. This could take a while.\n",
      "Collecting grpcio-status<2.0dev,>=1.33.2 (from google-api-core<3->tfx)\n",
      "  Obtaining dependency information for grpcio-status<2.0dev,>=1.33.2 from https://files.pythonhosted.org/packages/d0/3f/347d93056572fdbd64d4f0fc58a18d420763a7118f8b177437d9dab0ae6f/grpcio_status-1.57.0-py3-none-any.whl.metadata\n",
      "  Using cached grpcio_status-1.57.0-py3-none-any.whl.metadata (1.2 kB)\n",
      "  Obtaining dependency information for grpcio-status<2.0dev,>=1.33.2 from https://files.pythonhosted.org/packages/ef/16/3018689d96918e9c4c7407adf96b721df4d6748ba65db82c5eaa63564335/grpcio_status-1.56.2-py3-none-any.whl.metadata\n",
      "  Using cached grpcio_status-1.56.2-py3-none-any.whl.metadata (1.3 kB)\n",
      "  Obtaining dependency information for grpcio-status<2.0dev,>=1.33.2 from https://files.pythonhosted.org/packages/2b/21/aaff30111c5941fd9adb5abbf06e04a0e491a685f48ffb291f72ad595ec7/grpcio_status-1.56.0-py3-none-any.whl.metadata\n",
      "  Using cached grpcio_status-1.56.0-py3-none-any.whl.metadata (1.3 kB)\n",
      "  Obtaining dependency information for grpcio-status<2.0dev,>=1.33.2 from https://files.pythonhosted.org/packages/b6/c8/0efd0cf1ff62b3acc28619b9ba80a6ead4eb0ee42bb1c3b3841610af98a7/grpcio_status-1.55.3-py3-none-any.whl.metadata\n",
      "  Using cached grpcio_status-1.55.3-py3-none-any.whl.metadata (1.3 kB)\n",
      "  Obtaining dependency information for grpcio-status<2.0dev,>=1.33.2 from https://files.pythonhosted.org/packages/b9/ad/51cf59eb26ffa5360ba9dc318580b777e5dda1aa344ad34475103d97e5ac/grpcio_status-1.54.3-py3-none-any.whl.metadata\n",
      "  Using cached grpcio_status-1.54.3-py3-none-any.whl.metadata (1.3 kB)\n",
      "  Obtaining dependency information for grpcio-status<2.0dev,>=1.33.2 from https://files.pythonhosted.org/packages/5f/06/19520e0c6ab22fe09a0c8cfeabdf63b1ce6ea5d6ac88a65a2fa57b080976/grpcio_status-1.54.2-py3-none-any.whl.metadata\n",
      "  Using cached grpcio_status-1.54.2-py3-none-any.whl.metadata (1.3 kB)\n",
      "  Using cached grpcio_status-1.54.0-py3-none-any.whl (5.1 kB)\n",
      "INFO: pip is still looking at multiple versions of grpcio-status to determine which version is compatible with other requirements. This could take a while.\n",
      "  Obtaining dependency information for grpcio-status<2.0dev,>=1.33.2 from https://files.pythonhosted.org/packages/fb/c0/8ee53675cb1aecaa7fcbc9bea6575cb8c19a21dd0ce80fe6e5edb04426f4/grpcio_status-1.53.2-py3-none-any.whl.metadata\n",
      "  Using cached grpcio_status-1.53.2-py3-none-any.whl.metadata (1.3 kB)\n",
      "  Obtaining dependency information for grpcio-status<2.0dev,>=1.33.2 from https://files.pythonhosted.org/packages/61/14/6a4476403abaf954c0b5715de9cfdb7528143c5ac372316fa95704ae8551/grpcio_status-1.53.1-py3-none-any.whl.metadata\n",
      "  Using cached grpcio_status-1.53.1-py3-none-any.whl.metadata (1.3 kB)\n",
      "  Using cached grpcio_status-1.53.0-py3-none-any.whl (5.1 kB)\n",
      "  Using cached grpcio_status-1.51.3-py3-none-any.whl (5.1 kB)\n",
      "  Using cached grpcio_status-1.51.1-py3-none-any.whl (5.1 kB)\n",
      "INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.\n",
      "  Using cached grpcio_status-1.50.0-py3-none-any.whl (14 kB)\n",
      "  Using cached grpcio_status-1.49.1-py3-none-any.whl (14 kB)\n",
      "  Using cached grpcio_status-1.48.2-py3-none-any.whl (14 kB)\n",
      "Requirement already satisfied: debugpy>=1.0 in /opt/conda/lib/python3.8/site-packages (from ipykernel>=4.5.1->ipywidgets<8,>=7->tensorflow-model-analysis<0.46.0,>=0.45.0->tfx) (1.6.7)\n",
      "Requirement already satisfied: jupyter-client>=6.1.12 in /opt/conda/lib/python3.8/site-packages (from ipykernel>=4.5.1->ipywidgets<8,>=7->tensorflow-model-analysis<0.46.0,>=0.45.0->tfx) (8.2.0)\n",
      "Requirement already satisfied: nest-asyncio in /opt/conda/lib/python3.8/site-packages (from ipykernel>=4.5.1->ipywidgets<8,>=7->tensorflow-model-analysis<0.46.0,>=0.45.0->tfx) (1.5.6)\n",
      "Requirement already satisfied: pyzmq>=17 in /opt/conda/lib/python3.8/site-packages (from ipykernel>=4.5.1->ipywidgets<8,>=7->tensorflow-model-analysis<0.46.0,>=0.45.0->tfx) (25.0.2)\n",
      "Requirement already satisfied: tornado>=6.1 in /opt/conda/lib/python3.8/site-packages (from ipykernel>=4.5.1->ipywidgets<8,>=7->tensorflow-model-analysis<0.46.0,>=0.45.0->tfx) (6.3)\n",
      "Requirement already satisfied: parso<0.9.0,>=0.8.0 in /opt/conda/lib/python3.8/site-packages (from jedi>=0.16->ipython<8,>=7->tensorflow-model-analysis<0.46.0,>=0.45.0->tfx) (0.8.3)\n",
      "Requirement already satisfied: importlib-metadata>=4.4 in /opt/conda/lib/python3.8/site-packages (from markdown>=2.6.8->tensorboard<2.14,>=2.13->tensorflow<2.14,>=2.13.0->tfx) (5.2.0)\n",
      "Requirement already satisfied: fastjsonschema in /opt/conda/lib/python3.8/site-packages (from nbformat>=4.2.0->ipywidgets<8,>=7->tensorflow-model-analysis<0.46.0,>=0.45.0->tfx) (2.16.3)\n",
      "Requirement already satisfied: jsonschema>=2.6 in /home/chase/.local/lib/python3.8/site-packages (from nbformat>=4.2.0->ipywidgets<8,>=7->tensorflow-model-analysis<0.46.0,>=0.45.0->tfx) (3.2.0)\n",
      "Requirement already satisfied: jupyter-core in /opt/conda/lib/python3.8/site-packages (from nbformat>=4.2.0->ipywidgets<8,>=7->tensorflow-model-analysis<0.46.0,>=0.45.0->tfx) (5.3.0)\n",
      "Requirement already satisfied: ptyprocess>=0.5 in /opt/conda/lib/python3.8/site-packages (from pexpect>4.3->ipython<8,>=7->tensorflow-model-analysis<0.46.0,>=0.45.0->tfx) (0.7.0)\n",
      "Requirement already satisfied: wcwidth in /opt/conda/lib/python3.8/site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython<8,>=7->tensorflow-model-analysis<0.46.0,>=0.45.0->tfx) (0.2.6)\n",
      "Requirement already satisfied: notebook>=4.4.1 in /opt/conda/lib/python3.8/site-packages (from widgetsnbextension~=3.5.0->ipywidgets<8,>=7->tensorflow-model-analysis<0.46.0,>=0.45.0->tfx) (6.5.2)\n",
      "Collecting markdown-it-py>=2.2.0 (from rich->keras-core->keras-tuner<2,>=1.0.4->tfx)\n",
      "  Obtaining dependency information for markdown-it-py>=2.2.0 from https://files.pythonhosted.org/packages/42/d7/1ec15b46af6af88f19b8e5ffea08fa375d433c998b8a7639e76935c14f1f/markdown_it_py-3.0.0-py3-none-any.whl.metadata\n",
      "  Using cached markdown_it_py-3.0.0-py3-none-any.whl.metadata (6.9 kB)\n",
      "Collecting typing-extensions<5,>=3.10.0.2 (from tfx)\n",
      "  Using cached typing_extensions-4.5.0-py3-none-any.whl (27 kB)\n",
      "Requirement already satisfied: zipp>=0.5 in /opt/conda/lib/python3.8/site-packages (from importlib-metadata>=4.4->markdown>=2.6.8->tensorboard<2.14,>=2.13->tensorflow<2.14,>=2.13.0->tfx) (3.15.0)\n",
      "Requirement already satisfied: pyrsistent>=0.14.0 in /opt/conda/lib/python3.8/site-packages (from jsonschema>=2.6->nbformat>=4.2.0->ipywidgets<8,>=7->tensorflow-model-analysis<0.46.0,>=0.45.0->tfx) (0.19.3)\n",
      "Requirement already satisfied: platformdirs>=2.5 in /opt/conda/lib/python3.8/site-packages (from jupyter-core->nbformat>=4.2.0->ipywidgets<8,>=7->tensorflow-model-analysis<0.46.0,>=0.45.0->tfx) (3.2.0)\n",
      "Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich->keras-core->keras-tuner<2,>=1.0.4->tfx)\n",
      "  Using cached mdurl-0.1.2-py3-none-any.whl (10.0 kB)\n",
      "Requirement already satisfied: argon2-cffi in /opt/conda/lib/python3.8/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<8,>=7->tensorflow-model-analysis<0.46.0,>=0.45.0->tfx) (21.3.0)\n",
      "Requirement already satisfied: ipython-genutils in /opt/conda/lib/python3.8/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<8,>=7->tensorflow-model-analysis<0.46.0,>=0.45.0->tfx) (0.2.0)\n",
      "Requirement already satisfied: nbconvert>=5 in /opt/conda/lib/python3.8/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<8,>=7->tensorflow-model-analysis<0.46.0,>=0.45.0->tfx) (7.2.10)\n",
      "Requirement already satisfied: Send2Trash>=1.8.0 in /opt/conda/lib/python3.8/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<8,>=7->tensorflow-model-analysis<0.46.0,>=0.45.0->tfx) (1.8.0)\n",
      "Requirement already satisfied: terminado>=0.8.3 in /opt/conda/lib/python3.8/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<8,>=7->tensorflow-model-analysis<0.46.0,>=0.45.0->tfx) (0.17.1)\n",
      "Requirement already satisfied: prometheus-client in /opt/conda/lib/python3.8/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<8,>=7->tensorflow-model-analysis<0.46.0,>=0.45.0->tfx) (0.13.1)\n",
      "Requirement already satisfied: nbclassic>=0.4.7 in /opt/conda/lib/python3.8/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<8,>=7->tensorflow-model-analysis<0.46.0,>=0.45.0->tfx) (0.5.5)\n",
      "Requirement already satisfied: jupyter-server>=1.8 in /opt/conda/lib/python3.8/site-packages (from nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<8,>=7->tensorflow-model-analysis<0.46.0,>=0.45.0->tfx) (1.24.0)\n",
      "Requirement already satisfied: notebook-shim>=0.1.0 in /opt/conda/lib/python3.8/site-packages (from nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<8,>=7->tensorflow-model-analysis<0.46.0,>=0.45.0->tfx) (0.2.2)\n",
      "Requirement already satisfied: beautifulsoup4 in /opt/conda/lib/python3.8/site-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<8,>=7->tensorflow-model-analysis<0.46.0,>=0.45.0->tfx) (4.12.2)\n",
      "Requirement already satisfied: bleach in /opt/conda/lib/python3.8/site-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<8,>=7->tensorflow-model-analysis<0.46.0,>=0.45.0->tfx) (6.0.0)\n",
      "Requirement already satisfied: defusedxml in /opt/conda/lib/python3.8/site-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<8,>=7->tensorflow-model-analysis<0.46.0,>=0.45.0->tfx) (0.7.1)\n",
      "Requirement already satisfied: jupyterlab-pygments in /opt/conda/lib/python3.8/site-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<8,>=7->tensorflow-model-analysis<0.46.0,>=0.45.0->tfx) (0.2.2)\n",
      "Requirement already satisfied: mistune<3,>=2.0.3 in /opt/conda/lib/python3.8/site-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<8,>=7->tensorflow-model-analysis<0.46.0,>=0.45.0->tfx) (2.0.5)\n",
      "Requirement already satisfied: nbclient>=0.5.0 in /opt/conda/lib/python3.8/site-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<8,>=7->tensorflow-model-analysis<0.46.0,>=0.45.0->tfx) (0.7.3)\n",
      "Requirement already satisfied: pandocfilters>=1.4.1 in /opt/conda/lib/python3.8/site-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<8,>=7->tensorflow-model-analysis<0.46.0,>=0.45.0->tfx) (1.5.0)\n",
      "Requirement already satisfied: tinycss2 in /opt/conda/lib/python3.8/site-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<8,>=7->tensorflow-model-analysis<0.46.0,>=0.45.0->tfx) (1.2.1)\n",
      "Requirement already satisfied: argon2-cffi-bindings in /opt/conda/lib/python3.8/site-packages (from argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<8,>=7->tensorflow-model-analysis<0.46.0,>=0.45.0->tfx) (21.2.0)\n",
      "Requirement already satisfied: anyio<4,>=3.1.0 in /opt/conda/lib/python3.8/site-packages (from jupyter-server>=1.8->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<8,>=7->tensorflow-model-analysis<0.46.0,>=0.45.0->tfx) (3.6.2)\n",
      "Requirement already satisfied: cffi>=1.0.1 in /opt/conda/lib/python3.8/site-packages (from argon2-cffi-bindings->argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<8,>=7->tensorflow-model-analysis<0.46.0,>=0.45.0->tfx) (1.14.6)\n",
      "Requirement already satisfied: soupsieve>1.2 in /opt/conda/lib/python3.8/site-packages (from beautifulsoup4->nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<8,>=7->tensorflow-model-analysis<0.46.0,>=0.45.0->tfx) (2.4.1)\n",
      "Requirement already satisfied: webencodings in /opt/conda/lib/python3.8/site-packages (from bleach->nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<8,>=7->tensorflow-model-analysis<0.46.0,>=0.45.0->tfx) (0.5.1)\n",
      "Requirement already satisfied: sniffio>=1.1 in /opt/conda/lib/python3.8/site-packages (from anyio<4,>=3.1.0->jupyter-server>=1.8->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<8,>=7->tensorflow-model-analysis<0.46.0,>=0.45.0->tfx) (1.3.0)\n",
      "Requirement already satisfied: pycparser in /opt/conda/lib/python3.8/site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<8,>=7->tensorflow-model-analysis<0.46.0,>=0.45.0->tfx) (2.21)\n",
      "Using cached tfx-1.14.0-py3-none-any.whl (2.8 MB)\n",
      "Using cached ml_pipelines_sdk-1.14.0-py3-none-any.whl (1.5 MB)\n",
      "Using cached google_cloud_aiplatform-1.33.1-py2.py3-none-any.whl (2.9 MB)\n",
      "Using cached keras_tuner-1.4.2-py3-none-any.whl (127 kB)\n",
      "Using cached ml_metadata-1.14.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (7.5 MB)\n",
      "Using cached portpicker-1.6.0-py3-none-any.whl (16 kB)\n",
      "Using cached PyYAML-6.0.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (736 kB)\n"
     ]
    }
   ],
   "source": [
    "# Install the MLMD package. Notice we didn't have this pinned via Conda or within our container.\n",
    "!pip install tfx"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "7b6903e5-51d2-4ee7-99ab-9627de79e65c",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting tensorflow_model_analysis\n",
      "  Obtaining dependency information for tensorflow_model_analysis from https://files.pythonhosted.org/packages/35/56/9a2a677e178caa313fd3cc2ddc7df8558339504487baf1a726e7011dcbd6/tensorflow_model_analysis-0.45.0-py3-none-any.whl.metadata\n",
      "  Using cached tensorflow_model_analysis-0.45.0-py3-none-any.whl.metadata (19 kB)\n",
      "Requirement already satisfied: absl-py<2.0.0,>=0.9 in /opt/conda/lib/python3.8/site-packages (from tensorflow_model_analysis) (0.12.0)\n",
      "Collecting apache-beam[gcp]<3,>=2.47 (from tensorflow_model_analysis)\n",
      "  Obtaining dependency information for apache-beam[gcp]<3,>=2.47 from https://files.pythonhosted.org/packages/47/9c/ec3d6609d396ffd1b6f415e6bedb78874b837e3c47ab1d4472d2b0c5d899/apache_beam-2.50.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata\n",
      "  Using cached apache_beam-2.50.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.0 kB)\n",
      "Collecting ipython<8,>=7 (from tensorflow_model_analysis)\n",
      "  Using cached ipython-7.34.0-py3-none-any.whl (793 kB)\n",
      "Requirement already satisfied: ipywidgets<8,>=7 in /opt/conda/lib/python3.8/site-packages (from tensorflow_model_analysis) (7.6.3)\n",
      "Requirement already satisfied: numpy>=1.22.0 in /opt/conda/lib/python3.8/site-packages (from tensorflow_model_analysis) (1.22.4)\n",
      "Requirement already satisfied: pandas<2,>=1.0 in /opt/conda/lib/python3.8/site-packages (from tensorflow_model_analysis) (1.5.3)\n",
      "Requirement already satisfied: pillow>=9.4.0 in /opt/conda/lib/python3.8/site-packages (from tensorflow_model_analysis) (9.5.0)\n",
      "Collecting protobuf<5,>=3.20.3 (from tensorflow_model_analysis)\n",
      "  Obtaining dependency information for protobuf<5,>=3.20.3 from https://files.pythonhosted.org/packages/bb/c3/6a06208ecf0934ecaf509b51c52a6cf688586f54ae81ac65c56124571494/protobuf-4.24.3-cp37-abi3-manylinux2014_x86_64.whl.metadata\n",
      "  Using cached protobuf-4.24.3-cp37-abi3-manylinux2014_x86_64.whl.metadata (540 bytes)\n",
      "Collecting pyarrow<11,>=10 (from tensorflow_model_analysis)\n",
      "  Using cached pyarrow-10.0.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (36.0 MB)\n",
      "Requirement already satisfied: scipy<2,>=1.4.1 in /opt/conda/lib/python3.8/site-packages (from tensorflow_model_analysis) (1.7.0)\n",
      "Requirement already satisfied: six<2,>=1.12 in /opt/conda/lib/python3.8/site-packages (from tensorflow_model_analysis) (1.16.0)\n",
      "Requirement already satisfied: attrs<22,>=19.3.0 in /opt/conda/lib/python3.8/site-packages (from tensorflow_model_analysis) (20.3.0)\n",
      "Collecting tensorflow<3,>=2.13 (from tensorflow_model_analysis)\n",
      "  Obtaining dependency information for tensorflow<3,>=2.13 from https://files.pythonhosted.org/packages/c2/20/b15abac0be474f12cf51a104c9dd935b053081b502c103e9e947e8be7b84/tensorflow-2.13.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata\n",
      "  Using cached tensorflow-2.13.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.4 kB)\n",
      "Collecting tensorflow-metadata<1.15.0,>=1.14.0 (from tensorflow_model_analysis)\n",
      "  Obtaining dependency information for tensorflow-metadata<1.15.0,>=1.14.0 from https://files.pythonhosted.org/packages/41/23/3705c7139886c079ef4c0e3be56a5a1fb90e9ee413a4b7caaee0ee0ea6fe/tensorflow_metadata-1.14.0-py3-none-any.whl.metadata\n",
      "  Using cached tensorflow_metadata-1.14.0-py3-none-any.whl.metadata (2.1 kB)\n",
      "Collecting tfx-bsl<1.15.0,>=1.14.0 (from tensorflow_model_analysis)\n",
      "  Obtaining dependency information for tfx-bsl<1.15.0,>=1.14.0 from https://files.pythonhosted.org/packages/37/8c/3534124ad7cacc7cd128708fc629f52cd6e58e581f81c15bff13f6e916cb/tfx_bsl-1.14.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata\n",
      "  Using cached tfx_bsl-1.14.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (10 kB)\n",
      "Collecting crcmod<2.0,>=1.7 (from apache-beam[gcp]<3,>=2.47->tensorflow_model_analysis)\n",
      "  Using cached crcmod-1.7-py3-none-any.whl\n",
      "Collecting orjson<4.0 (from apache-beam[gcp]<3,>=2.47->tensorflow_model_analysis)\n",
      "  Obtaining dependency information for orjson<4.0 from https://files.pythonhosted.org/packages/cc/b4/324754a9e255295c0b5966f78999822e180a0fa2c22fd96edefac9dd8313/orjson-3.9.7-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata\n",
      "  Using cached orjson-3.9.7-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (49 kB)\n",
      "Collecting dill<0.3.2,>=0.3.1.1 (from apache-beam[gcp]<3,>=2.47->tensorflow_model_analysis)\n",
      "  Using cached dill-0.3.1.1-py3-none-any.whl\n",
      "Collecting cloudpickle~=2.2.1 (from apache-beam[gcp]<3,>=2.47->tensorflow_model_analysis)\n",
      "  Using cached cloudpickle-2.2.1-py3-none-any.whl (25 kB)\n",
      "Requirement already satisfied: fastavro<2,>=0.23.6 in /opt/conda/lib/python3.8/site-packages (from apache-beam[gcp]<3,>=2.47->tensorflow_model_analysis) (1.7.3)\n",
      "Collecting fasteners<1.0,>=0.3 (from apache-beam[gcp]<3,>=2.47->tensorflow_model_analysis)\n",
      "  Obtaining dependency information for fasteners<1.0,>=0.3 from https://files.pythonhosted.org/packages/61/bf/fd60001b3abc5222d8eaa4a204cd8c0ae78e75adc688f33ce4bf25b7fafa/fasteners-0.19-py3-none-any.whl.metadata\n",
      "  Using cached fasteners-0.19-py3-none-any.whl.metadata (4.9 kB)\n",
      "Requirement already satisfied: grpcio!=1.48.0,<2,>=1.33.1 in /opt/conda/lib/python3.8/site-packages (from apache-beam[gcp]<3,>=2.47->tensorflow_model_analysis) (1.54.0)\n",
      "Collecting hdfs<3.0.0,>=2.1.0 (from apache-beam[gcp]<3,>=2.47->tensorflow_model_analysis)\n",
      "  Using cached hdfs-2.7.2-py3-none-any.whl\n",
      "Requirement already satisfied: httplib2<0.23.0,>=0.8 in /opt/conda/lib/python3.8/site-packages (from apache-beam[gcp]<3,>=2.47->tensorflow_model_analysis) (0.22.0)\n",
      "Collecting objsize<0.7.0,>=0.6.1 (from apache-beam[gcp]<3,>=2.47->tensorflow_model_analysis)\n",
      "  Using cached objsize-0.6.1-py3-none-any.whl (9.3 kB)\n",
      "Collecting pymongo<5.0.0,>=3.8.0 (from apache-beam[gcp]<3,>=2.47->tensorflow_model_analysis)\n",
      "  Obtaining dependency information for pymongo<5.0.0,>=3.8.0 from https://files.pythonhosted.org/packages/bf/b7/63cebc24f4690b85d0c91fe11a32ad14e791ff499f4054cde8f1a4ea08dc/pymongo-4.5.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata\n",
      "  Using cached pymongo-4.5.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (22 kB)\n",
      "Requirement already satisfied: proto-plus<2,>=1.7.1 in /opt/conda/lib/python3.8/site-packages (from apache-beam[gcp]<3,>=2.47->tensorflow_model_analysis) (1.22.2)\n",
      "Collecting protobuf<5,>=3.20.3 (from tensorflow_model_analysis)\n",
      "  Obtaining dependency information for protobuf<5,>=3.20.3 from https://files.pythonhosted.org/packages/01/cb/445b3e465abdb8042a41957dc8f60c54620dc7540dbcf9b458a921531ca2/protobuf-4.23.4-cp37-abi3-manylinux2014_x86_64.whl.metadata\n",
      "  Using cached protobuf-4.23.4-cp37-abi3-manylinux2014_x86_64.whl.metadata (540 bytes)\n",
      "Collecting pydot<2,>=1.2.0 (from apache-beam[gcp]<3,>=2.47->tensorflow_model_analysis)\n",
      "  Using cached pydot-1.4.2-py2.py3-none-any.whl (21 kB)\n",
      "Requirement already satisfied: python-dateutil<3,>=2.8.0 in /opt/conda/lib/python3.8/site-packages (from apache-beam[gcp]<3,>=2.47->tensorflow_model_analysis) (2.8.2)\n",
      "Requirement already satisfied: pytz>=2018.3 in /opt/conda/lib/python3.8/site-packages (from apache-beam[gcp]<3,>=2.47->tensorflow_model_analysis) (2022.7.1)\n",
      "Collecting regex>=2020.6.8 (from apache-beam[gcp]<3,>=2.47->tensorflow_model_analysis)\n",
      "  Obtaining dependency information for regex>=2020.6.8 from https://files.pythonhosted.org/packages/1f/5c/374ac3fa3c7ed9a967ad273a5e841897ef6b10aa6aad938ff10717a3e2a3/regex-2023.8.8-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata\n",
      "  Using cached regex-2023.8.8-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (40 kB)\n",
      "Requirement already satisfied: requests<3.0.0,>=2.24.0 in /opt/conda/lib/python3.8/site-packages (from apache-beam[gcp]<3,>=2.47->tensorflow_model_analysis) (2.28.2)\n",
      "Requirement already satisfied: typing-extensions>=3.7.0 in /home/chase/.local/lib/python3.8/site-packages (from apache-beam[gcp]<3,>=2.47->tensorflow_model_analysis) (3.10.0.2)\n",
      "Requirement already satisfied: zstandard<1,>=0.18.0 in /opt/conda/lib/python3.8/site-packages (from apache-beam[gcp]<3,>=2.47->tensorflow_model_analysis) (0.19.0)\n",
      "Requirement already satisfied: cachetools<6,>=3.1.0 in /home/chase/.local/lib/python3.8/site-packages (from apache-beam[gcp]<3,>=2.47->tensorflow_model_analysis) (4.2.4)\n",
      "Requirement already satisfied: google-api-core<3,>=2.0.0 in /home/chase/.local/lib/python3.8/site-packages (from apache-beam[gcp]<3,>=2.47->tensorflow_model_analysis) (2.10.2)\n",
      "Collecting google-apitools<0.5.32,>=0.5.31 (from apache-beam[gcp]<3,>=2.47->tensorflow_model_analysis)\n",
      "  Using cached google_apitools-0.5.31-py3-none-any.whl\n",
      "Requirement already satisfied: google-auth<3,>=1.18.0 in /home/chase/.local/lib/python3.8/site-packages (from apache-beam[gcp]<3,>=2.47->tensorflow_model_analysis) (1.35.0)\n",
      "Requirement already satisfied: google-auth-httplib2<0.2.0,>=0.1.0 in /opt/conda/lib/python3.8/site-packages (from apache-beam[gcp]<3,>=2.47->tensorflow_model_analysis) (0.1.0)\n",
      "Collecting google-cloud-datastore<3,>=2.0.0 (from apache-beam[gcp]<3,>=2.47->tensorflow_model_analysis)\n",
      "  Obtaining dependency information for google-cloud-datastore<3,>=2.0.0 from https://files.pythonhosted.org/packages/e6/e3/9e19e26b4fc61aa64a73d097c9e5ce3b4cbb62d7d0ea2c0554b2105b54d6/google_cloud_datastore-2.18.0-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_cloud_datastore-2.18.0-py2.py3-none-any.whl.metadata (5.5 kB)\n",
      "Collecting google-cloud-pubsub<3,>=2.1.0 (from apache-beam[gcp]<3,>=2.47->tensorflow_model_analysis)\n",
      "  Obtaining dependency information for google-cloud-pubsub<3,>=2.1.0 from https://files.pythonhosted.org/packages/d2/58/fbdedd07206514f09f029458d95d391829b09399c1459d8892e6e20022d1/google_cloud_pubsub-2.18.4-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_cloud_pubsub-2.18.4-py2.py3-none-any.whl.metadata (9.2 kB)\n",
      "Collecting google-cloud-pubsublite<2,>=1.2.0 (from apache-beam[gcp]<3,>=2.47->tensorflow_model_analysis)\n",
      "  Obtaining dependency information for google-cloud-pubsublite<2,>=1.2.0 from https://files.pythonhosted.org/packages/2d/d6/91f605fc67e9d0b4e419c4f291adff15c2f241bf3d70abe8068688599d60/google_cloud_pubsublite-1.8.3-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_cloud_pubsublite-1.8.3-py2.py3-none-any.whl.metadata (5.5 kB)\n",
      "Collecting google-cloud-bigquery<4,>=2.0.0 (from apache-beam[gcp]<3,>=2.47->tensorflow_model_analysis)\n",
      "  Obtaining dependency information for google-cloud-bigquery<4,>=2.0.0 from https://files.pythonhosted.org/packages/cc/6a/d0ef792288f2fa2cfea80899a82de302b3332dfda41984fe114e2cfbf700/google_cloud_bigquery-3.11.4-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_cloud_bigquery-3.11.4-py2.py3-none-any.whl.metadata (8.5 kB)\n",
      "Collecting google-cloud-bigquery-storage<3,>=2.6.3 (from apache-beam[gcp]<3,>=2.47->tensorflow_model_analysis)\n",
      "  Obtaining dependency information for google-cloud-bigquery-storage<3,>=2.6.3 from https://files.pythonhosted.org/packages/83/eb/e5016412a9c6ac26b46480f83d58112b99b48c0e38ae040b46f8795dea6f/google_cloud_bigquery_storage-2.22.0-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_cloud_bigquery_storage-2.22.0-py2.py3-none-any.whl.metadata (5.4 kB)\n",
      "Requirement already satisfied: google-cloud-core<3,>=2.0.0 in /opt/conda/lib/python3.8/site-packages (from apache-beam[gcp]<3,>=2.47->tensorflow_model_analysis) (2.3.2)\n",
      "Collecting google-cloud-bigtable<3,>=2.19.0 (from apache-beam[gcp]<3,>=2.47->tensorflow_model_analysis)\n",
      "  Obtaining dependency information for google-cloud-bigtable<3,>=2.19.0 from https://files.pythonhosted.org/packages/f1/2e/fcdd3aed46825c04bc93c0223fff674059e6a789cfda5374948bea1a3f6e/google_cloud_bigtable-2.21.0-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_cloud_bigtable-2.21.0-py2.py3-none-any.whl.metadata (5.1 kB)\n",
      "Collecting google-cloud-spanner<4,>=3.0.0 (from apache-beam[gcp]<3,>=2.47->tensorflow_model_analysis)\n",
      "  Obtaining dependency information for google-cloud-spanner<4,>=3.0.0 from https://files.pythonhosted.org/packages/fd/77/527bbb6c103ef5e8e0d49d8000e337d3ce4ed66a373af915b0170012de30/google_cloud_spanner-3.40.1-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_cloud_spanner-3.40.1-py2.py3-none-any.whl.metadata (10 kB)\n",
      "Collecting google-cloud-dlp<4,>=3.0.0 (from apache-beam[gcp]<3,>=2.47->tensorflow_model_analysis)\n",
      "  Obtaining dependency information for google-cloud-dlp<4,>=3.0.0 from https://files.pythonhosted.org/packages/9a/2c/5a62598d1696246c056e512ac69983e0d736cd2cd2ac1107075743a4ec48/google_cloud_dlp-3.12.3-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_cloud_dlp-3.12.3-py2.py3-none-any.whl.metadata (5.2 kB)\n",
      "Collecting google-cloud-language<3,>=2.0 (from apache-beam[gcp]<3,>=2.47->tensorflow_model_analysis)\n",
      "  Obtaining dependency information for google-cloud-language<3,>=2.0 from https://files.pythonhosted.org/packages/19/4c/8a42006ec29f26d1d0f47f5fdebe7138a700eda8e3668d53ffcb55c9a774/google_cloud_language-2.11.1-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_cloud_language-2.11.1-py2.py3-none-any.whl.metadata (5.3 kB)\n",
      "Collecting google-cloud-videointelligence<3,>=2.0 (from apache-beam[gcp]<3,>=2.47->tensorflow_model_analysis)\n",
      "  Obtaining dependency information for google-cloud-videointelligence<3,>=2.0 from https://files.pythonhosted.org/packages/ca/0e/ce99f6c36d5e7ccbc5827d714a947da5b864a30e060f2e5dddad4166f663/google_cloud_videointelligence-2.11.4-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_cloud_videointelligence-2.11.4-py2.py3-none-any.whl.metadata (5.6 kB)\n",
      "Collecting google-cloud-vision<4,>=2 (from apache-beam[gcp]<3,>=2.47->tensorflow_model_analysis)\n",
      "  Obtaining dependency information for google-cloud-vision<4,>=2 from https://files.pythonhosted.org/packages/14/16/e3ea36b6989e0cff58c2cc38261b9b5133a58d1fb08d64fb85fc552f3466/google_cloud_vision-3.4.4-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_cloud_vision-3.4.4-py2.py3-none-any.whl.metadata (6.2 kB)\n",
      "Collecting google-cloud-recommendations-ai<0.11.0,>=0.1.0 (from apache-beam[gcp]<3,>=2.47->tensorflow_model_analysis)\n",
      "  Obtaining dependency information for google-cloud-recommendations-ai<0.11.0,>=0.1.0 from https://files.pythonhosted.org/packages/f9/7f/c6554fcbc09a861e11214df359c1d048791c8a2d6b8909be023ba5fe0997/google_cloud_recommendations_ai-0.10.5-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_cloud_recommendations_ai-0.10.5-py2.py3-none-any.whl.metadata (5.2 kB)\n",
      "Collecting google-cloud-aiplatform<2.0,>=1.26.0 (from apache-beam[gcp]<3,>=2.47->tensorflow_model_analysis)\n",
      "  Obtaining dependency information for google-cloud-aiplatform<2.0,>=1.26.0 from https://files.pythonhosted.org/packages/d3/66/10a048f9327fc9efb16233ab009960dc8717327e3359e12ca94f038b22b1/google_cloud_aiplatform-1.33.1-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_cloud_aiplatform-1.33.1-py2.py3-none-any.whl.metadata (27 kB)\n",
      "Requirement already satisfied: setuptools>=18.5 in /opt/conda/lib/python3.8/site-packages (from ipython<8,>=7->tensorflow_model_analysis) (67.7.1)\n",
      "Requirement already satisfied: jedi>=0.16 in /opt/conda/lib/python3.8/site-packages (from ipython<8,>=7->tensorflow_model_analysis) (0.18.2)\n",
      "Requirement already satisfied: decorator in /opt/conda/lib/python3.8/site-packages (from ipython<8,>=7->tensorflow_model_analysis) (5.1.1)\n",
      "Requirement already satisfied: pickleshare in /opt/conda/lib/python3.8/site-packages (from ipython<8,>=7->tensorflow_model_analysis) (0.7.5)\n",
      "Requirement already satisfied: traitlets>=4.2 in /opt/conda/lib/python3.8/site-packages (from ipython<8,>=7->tensorflow_model_analysis) (5.9.0)\n",
      "Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /opt/conda/lib/python3.8/site-packages (from ipython<8,>=7->tensorflow_model_analysis) (3.0.38)\n",
      "Requirement already satisfied: pygments in /opt/conda/lib/python3.8/site-packages (from ipython<8,>=7->tensorflow_model_analysis) (2.15.1)\n",
      "Requirement already satisfied: backcall in /opt/conda/lib/python3.8/site-packages (from ipython<8,>=7->tensorflow_model_analysis) (0.2.0)\n",
      "Requirement already satisfied: matplotlib-inline in /opt/conda/lib/python3.8/site-packages (from ipython<8,>=7->tensorflow_model_analysis) (0.1.6)\n",
      "Requirement already satisfied: pexpect>4.3 in /opt/conda/lib/python3.8/site-packages (from ipython<8,>=7->tensorflow_model_analysis) (4.8.0)\n",
      "Requirement already satisfied: ipykernel>=4.5.1 in /opt/conda/lib/python3.8/site-packages (from ipywidgets<8,>=7->tensorflow_model_analysis) (6.15.0)\n",
      "Requirement already satisfied: nbformat>=4.2.0 in /opt/conda/lib/python3.8/site-packages (from ipywidgets<8,>=7->tensorflow_model_analysis) (5.7.3)\n",
      "Requirement already satisfied: widgetsnbextension~=3.5.0 in /opt/conda/lib/python3.8/site-packages (from ipywidgets<8,>=7->tensorflow_model_analysis) (3.5.2)\n",
      "Requirement already satisfied: jupyterlab-widgets>=1.0.0 in /opt/conda/lib/python3.8/site-packages (from ipywidgets<8,>=7->tensorflow_model_analysis) (3.0.7)\n",
      "Collecting absl-py<2.0.0,>=0.9 (from tensorflow_model_analysis)\n",
      "  Using cached absl_py-1.4.0-py3-none-any.whl (126 kB)\n",
      "Requirement already satisfied: astunparse>=1.6.0 in /opt/conda/lib/python3.8/site-packages (from tensorflow<3,>=2.13->tensorflow_model_analysis) (1.6.3)\n",
      "Collecting flatbuffers>=23.1.21 (from tensorflow<3,>=2.13->tensorflow_model_analysis)\n",
      "  Obtaining dependency information for flatbuffers>=23.1.21 from https://files.pythonhosted.org/packages/6f/12/d5c79ee252793ffe845d58a913197bfa02ae9a0b5c9bc3dc4b58d477b9e7/flatbuffers-23.5.26-py2.py3-none-any.whl.metadata\n",
      "  Using cached flatbuffers-23.5.26-py2.py3-none-any.whl.metadata (850 bytes)\n",
      "Requirement already satisfied: gast<=0.4.0,>=0.2.1 in /opt/conda/lib/python3.8/site-packages (from tensorflow<3,>=2.13->tensorflow_model_analysis) (0.4.0)\n",
      "Requirement already satisfied: google-pasta>=0.1.1 in /opt/conda/lib/python3.8/site-packages (from tensorflow<3,>=2.13->tensorflow_model_analysis) (0.2.0)\n",
      "Requirement already satisfied: h5py>=2.9.0 in /opt/conda/lib/python3.8/site-packages (from tensorflow<3,>=2.13->tensorflow_model_analysis) (3.8.0)\n",
      "Collecting keras<2.14,>=2.13.1 (from tensorflow<3,>=2.13->tensorflow_model_analysis)\n",
      "  Obtaining dependency information for keras<2.14,>=2.13.1 from https://files.pythonhosted.org/packages/2e/f3/19da7511b45e80216cbbd9467137b2d28919c58ba1ccb971435cb631e470/keras-2.13.1-py3-none-any.whl.metadata\n",
      "  Using cached keras-2.13.1-py3-none-any.whl.metadata (2.4 kB)\n",
      "Requirement already satisfied: libclang>=13.0.0 in /opt/conda/lib/python3.8/site-packages (from tensorflow<3,>=2.13->tensorflow_model_analysis) (16.0.0)\n",
      "Requirement already satisfied: opt-einsum>=2.3.2 in /opt/conda/lib/python3.8/site-packages (from tensorflow<3,>=2.13->tensorflow_model_analysis) (3.3.0)\n",
      "Requirement already satisfied: packaging in /opt/conda/lib/python3.8/site-packages (from tensorflow<3,>=2.13->tensorflow_model_analysis) (22.0)\n",
      "Collecting tensorboard<2.14,>=2.13 (from tensorflow<3,>=2.13->tensorflow_model_analysis)\n",
      "  Using cached tensorboard-2.13.0-py3-none-any.whl (5.6 MB)\n",
      "Collecting tensorflow-estimator<2.14,>=2.13.0 (from tensorflow<3,>=2.13->tensorflow_model_analysis)\n",
      "  Obtaining dependency information for tensorflow-estimator<2.14,>=2.13.0 from https://files.pythonhosted.org/packages/72/5c/c318268d96791c6222ad7df1651bbd1b2409139afeb6f468c0f327177016/tensorflow_estimator-2.13.0-py2.py3-none-any.whl.metadata\n",
      "  Using cached tensorflow_estimator-2.13.0-py2.py3-none-any.whl.metadata (1.3 kB)\n",
      "Requirement already satisfied: termcolor>=1.1.0 in /opt/conda/lib/python3.8/site-packages (from tensorflow<3,>=2.13->tensorflow_model_analysis) (2.2.0)\n",
      "Requirement already satisfied: wrapt>=1.11.0 in /opt/conda/lib/python3.8/site-packages (from tensorflow<3,>=2.13->tensorflow_model_analysis) (1.15.0)\n",
      "Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /opt/conda/lib/python3.8/site-packages (from tensorflow<3,>=2.13->tensorflow_model_analysis) (0.32.0)\n",
      "Requirement already satisfied: googleapis-common-protos<2,>=1.52.0 in /opt/conda/lib/python3.8/site-packages (from tensorflow-metadata<1.15.0,>=1.14.0->tensorflow_model_analysis) (1.59.0)\n",
      "Collecting protobuf<5,>=3.20.3 (from tensorflow_model_analysis)\n",
      "  Using cached protobuf-3.20.3-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.whl (1.0 MB)\n",
      "Requirement already satisfied: google-api-python-client<2,>=1.7.11 in /opt/conda/lib/python3.8/site-packages (from tfx-bsl<1.15.0,>=1.14.0->tensorflow_model_analysis) (1.12.11)\n",
      "Collecting tensorflow-serving-api<3,>=2.13.0 (from tfx-bsl<1.15.0,>=1.14.0->tensorflow_model_analysis)\n",
      "  Obtaining dependency information for tensorflow-serving-api<3,>=2.13.0 from https://files.pythonhosted.org/packages/71/fe/4004906ca558255673fab41a1bb2189ca6454417487a8608100677c8cc15/tensorflow_serving_api-2.13.0-py2.py3-none-any.whl.metadata\n",
      "  Using cached tensorflow_serving_api-2.13.0-py2.py3-none-any.whl.metadata (1.8 kB)\n",
      "Requirement already satisfied: wheel<1.0,>=0.23.0 in /opt/conda/lib/python3.8/site-packages (from astunparse>=1.6.0->tensorflow<3,>=2.13->tensorflow_model_analysis) (0.40.0)\n",
      "Requirement already satisfied: uritemplate<4dev,>=3.0.0 in /opt/conda/lib/python3.8/site-packages (from google-api-python-client<2,>=1.7.11->tfx-bsl<1.15.0,>=1.14.0->tensorflow_model_analysis) (3.0.1)\n",
      "Collecting oauth2client>=1.4.12 (from google-apitools<0.5.32,>=0.5.31->apache-beam[gcp]<3,>=2.47->tensorflow_model_analysis)\n",
      "  Using cached oauth2client-4.1.3-py2.py3-none-any.whl (98 kB)\n",
      "Requirement already satisfied: pyasn1-modules>=0.2.1 in /opt/conda/lib/python3.8/site-packages (from google-auth<3,>=1.18.0->apache-beam[gcp]<3,>=2.47->tensorflow_model_analysis) (0.3.0)\n",
      "Requirement already satisfied: rsa<5,>=3.1.4 in /opt/conda/lib/python3.8/site-packages (from google-auth<3,>=1.18.0->apache-beam[gcp]<3,>=2.47->tensorflow_model_analysis) (4.9)\n",
      "Requirement already satisfied: google-cloud-storage<3.0.0dev,>=1.32.0 in /home/chase/.local/lib/python3.8/site-packages (from google-cloud-aiplatform<2.0,>=1.26.0->apache-beam[gcp]<3,>=2.47->tensorflow_model_analysis) (1.44.0)\n",
      "Collecting google-cloud-resource-manager<3.0.0dev,>=1.3.3 (from google-cloud-aiplatform<2.0,>=1.26.0->apache-beam[gcp]<3,>=2.47->tensorflow_model_analysis)\n",
      "  Obtaining dependency information for google-cloud-resource-manager<3.0.0dev,>=1.3.3 from https://files.pythonhosted.org/packages/8b/9c/6807473e69fddc9bf33413b7db966fbcfeb0deade2f5ed324cef2b98ec16/google_cloud_resource_manager-1.10.4-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_cloud_resource_manager-1.10.4-py2.py3-none-any.whl.metadata (5.2 kB)\n",
      "Collecting shapely<2.0.0 (from google-cloud-aiplatform<2.0,>=1.26.0->apache-beam[gcp]<3,>=2.47->tensorflow_model_analysis)\n",
      "  Using cached Shapely-1.8.5.post1-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (2.1 MB)\n",
      "Requirement already satisfied: google-resumable-media<3.0dev,>=0.6.0 in /opt/conda/lib/python3.8/site-packages (from google-cloud-bigquery<4,>=2.0.0->apache-beam[gcp]<3,>=2.47->tensorflow_model_analysis) (2.4.1)\n",
      "Collecting google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0dev,>=1.32.0 (from google-cloud-aiplatform<2.0,>=1.26.0->apache-beam[gcp]<3,>=2.47->tensorflow_model_analysis)\n",
      "  Obtaining dependency information for google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0dev,>=1.32.0 from https://files.pythonhosted.org/packages/4d/ce/4fd62ea66b3508debc795e475336ce915929765870f0ad52328426ba016e/google_api_core-2.12.0-py3-none-any.whl.metadata\n",
      "  Using cached google_api_core-2.12.0-py3-none-any.whl.metadata (2.7 kB)\n",
      "Collecting grpc-google-iam-v1<1.0.0dev,>=0.12.4 (from google-cloud-bigtable<3,>=2.19.0->apache-beam[gcp]<3,>=2.47->tensorflow_model_analysis)\n",
      "  Using cached grpc_google_iam_v1-0.12.6-py2.py3-none-any.whl (26 kB)\n",
      "Collecting grpcio-status>=1.33.2 (from google-cloud-pubsub<3,>=2.1.0->apache-beam[gcp]<3,>=2.47->tensorflow_model_analysis)\n",
      "  Obtaining dependency information for grpcio-status>=1.33.2 from https://files.pythonhosted.org/packages/f6/48/2bcf11bc2df159564eac099ea38d80663d291a56fa2f2f561d08bf083dfa/grpcio_status-1.58.0-py3-none-any.whl.metadata\n",
      "  Using cached grpcio_status-1.58.0-py3-none-any.whl.metadata (1.3 kB)\n",
      "Collecting overrides<7.0.0,>=6.0.1 (from google-cloud-pubsublite<2,>=1.2.0->apache-beam[gcp]<3,>=2.47->tensorflow_model_analysis)\n",
      "  Using cached overrides-6.5.0-py3-none-any.whl (17 kB)\n",
      "Requirement already satisfied: sqlparse>=0.4.4 in /opt/conda/lib/python3.8/site-packages (from google-cloud-spanner<4,>=3.0.0->apache-beam[gcp]<3,>=2.47->tensorflow_model_analysis) (0.4.4)\n",
      "Collecting docopt (from hdfs<3.0.0,>=2.1.0->apache-beam[gcp]<3,>=2.47->tensorflow_model_analysis)\n",
      "  Using cached docopt-0.6.2-py2.py3-none-any.whl\n",
      "Requirement already satisfied: pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2 in /opt/conda/lib/python3.8/site-packages (from httplib2<0.23.0,>=0.8->apache-beam[gcp]<3,>=2.47->tensorflow_model_analysis) (3.0.9)\n",
      "Requirement already satisfied: debugpy>=1.0 in /opt/conda/lib/python3.8/site-packages (from ipykernel>=4.5.1->ipywidgets<8,>=7->tensorflow_model_analysis) (1.6.7)\n",
      "Requirement already satisfied: jupyter-client>=6.1.12 in /opt/conda/lib/python3.8/site-packages (from ipykernel>=4.5.1->ipywidgets<8,>=7->tensorflow_model_analysis) (8.2.0)\n",
      "Requirement already satisfied: nest-asyncio in /opt/conda/lib/python3.8/site-packages (from ipykernel>=4.5.1->ipywidgets<8,>=7->tensorflow_model_analysis) (1.5.6)\n",
      "Requirement already satisfied: psutil in /opt/conda/lib/python3.8/site-packages (from ipykernel>=4.5.1->ipywidgets<8,>=7->tensorflow_model_analysis) (5.9.5)\n",
      "Requirement already satisfied: pyzmq>=17 in /opt/conda/lib/python3.8/site-packages (from ipykernel>=4.5.1->ipywidgets<8,>=7->tensorflow_model_analysis) (25.0.2)\n",
      "Requirement already satisfied: tornado>=6.1 in /opt/conda/lib/python3.8/site-packages (from ipykernel>=4.5.1->ipywidgets<8,>=7->tensorflow_model_analysis) (6.3)\n",
      "Requirement already satisfied: parso<0.9.0,>=0.8.0 in /opt/conda/lib/python3.8/site-packages (from jedi>=0.16->ipython<8,>=7->tensorflow_model_analysis) (0.8.3)\n",
      "Requirement already satisfied: fastjsonschema in /opt/conda/lib/python3.8/site-packages (from nbformat>=4.2.0->ipywidgets<8,>=7->tensorflow_model_analysis) (2.16.3)\n",
      "Requirement already satisfied: jsonschema>=2.6 in /home/chase/.local/lib/python3.8/site-packages (from nbformat>=4.2.0->ipywidgets<8,>=7->tensorflow_model_analysis) (3.2.0)\n",
      "Requirement already satisfied: jupyter-core in /opt/conda/lib/python3.8/site-packages (from nbformat>=4.2.0->ipywidgets<8,>=7->tensorflow_model_analysis) (5.3.0)\n",
      "Requirement already satisfied: ptyprocess>=0.5 in /opt/conda/lib/python3.8/site-packages (from pexpect>4.3->ipython<8,>=7->tensorflow_model_analysis) (0.7.0)\n",
      "Requirement already satisfied: wcwidth in /opt/conda/lib/python3.8/site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython<8,>=7->tensorflow_model_analysis) (0.2.6)\n",
      "Collecting dnspython<3.0.0,>=1.16.0 (from pymongo<5.0.0,>=3.8.0->apache-beam[gcp]<3,>=2.47->tensorflow_model_analysis)\n",
      "  Obtaining dependency information for dnspython<3.0.0,>=1.16.0 from https://files.pythonhosted.org/packages/f6/b4/0a9bee52c50f226a3cbfb54263d02bb421c7f2adc136520729c2c689c1e5/dnspython-2.4.2-py3-none-any.whl.metadata\n",
      "  Using cached dnspython-2.4.2-py3-none-any.whl.metadata (4.9 kB)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in /opt/conda/lib/python3.8/site-packages (from requests<3.0.0,>=2.24.0->apache-beam[gcp]<3,>=2.47->tensorflow_model_analysis) (3.1.0)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.8/site-packages (from requests<3.0.0,>=2.24.0->apache-beam[gcp]<3,>=2.47->tensorflow_model_analysis) (3.4)\n",
      "Requirement already satisfied: urllib3<1.27,>=1.21.1 in /opt/conda/lib/python3.8/site-packages (from requests<3.0.0,>=2.24.0->apache-beam[gcp]<3,>=2.47->tensorflow_model_analysis) (1.26.15)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.8/site-packages (from requests<3.0.0,>=2.24.0->apache-beam[gcp]<3,>=2.47->tensorflow_model_analysis) (2022.12.7)\n",
      "Requirement already satisfied: google-auth-oauthlib<1.1,>=0.5 in /opt/conda/lib/python3.8/site-packages (from tensorboard<2.14,>=2.13->tensorflow<3,>=2.13->tensorflow_model_analysis) (1.0.0)\n",
      "Requirement already satisfied: markdown>=2.6.8 in /opt/conda/lib/python3.8/site-packages (from tensorboard<2.14,>=2.13->tensorflow<3,>=2.13->tensorflow_model_analysis) (3.4.3)\n",
      "Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /opt/conda/lib/python3.8/site-packages (from tensorboard<2.14,>=2.13->tensorflow<3,>=2.13->tensorflow_model_analysis) (0.7.0)\n",
      "Requirement already satisfied: werkzeug>=1.0.1 in /opt/conda/lib/python3.8/site-packages (from tensorboard<2.14,>=2.13->tensorflow<3,>=2.13->tensorflow_model_analysis) (2.2.3)\n",
      "Requirement already satisfied: notebook>=4.4.1 in /opt/conda/lib/python3.8/site-packages (from widgetsnbextension~=3.5.0->ipywidgets<8,>=7->tensorflow_model_analysis) (6.5.2)\n",
      "Collecting google-auth<3,>=1.18.0 (from apache-beam[gcp]<3,>=2.47->tensorflow_model_analysis)\n",
      "  Obtaining dependency information for google-auth<3,>=1.18.0 from https://files.pythonhosted.org/packages/23/e4/abbb8763fdf6279c471443251b3f847ee9a172d1776742b266fe6de7ac86/google_auth-2.23.1-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_auth-2.23.1-py2.py3-none-any.whl.metadata (4.2 kB)\n",
      "INFO: pip is looking at multiple versions of google-auth to determine which version is compatible with other requirements. This could take a while.\n",
      "  Obtaining dependency information for google-auth<3,>=1.18.0 from https://files.pythonhosted.org/packages/9d/44/5a992cb9d7bf8aaae73bc5adaf721ad08731c9d00c1c17999a8691404b0c/google_auth-2.23.0-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_auth-2.23.0-py2.py3-none-any.whl.metadata (4.2 kB)\n",
      "Requirement already satisfied: requests-oauthlib>=0.7.0 in /opt/conda/lib/python3.8/site-packages (from google-auth-oauthlib<1.1,>=0.5->tensorboard<2.14,>=2.13->tensorflow<3,>=2.13->tensorflow_model_analysis) (1.3.1)\n",
      "Requirement already satisfied: google-crc32c<2.0dev,>=1.0 in /opt/conda/lib/python3.8/site-packages (from google-resumable-media<3.0dev,>=0.6.0->google-cloud-bigquery<4,>=2.0.0->apache-beam[gcp]<3,>=2.47->tensorflow_model_analysis) (1.5.0)\n",
      "INFO: pip is looking at multiple versions of grpcio-status to determine which version is compatible with other requirements. This could take a while.\n",
      "Collecting grpcio-status>=1.33.2 (from google-cloud-pubsub<3,>=2.1.0->apache-beam[gcp]<3,>=2.47->tensorflow_model_analysis)\n",
      "  Obtaining dependency information for grpcio-status>=1.33.2 from https://files.pythonhosted.org/packages/d0/3f/347d93056572fdbd64d4f0fc58a18d420763a7118f8b177437d9dab0ae6f/grpcio_status-1.57.0-py3-none-any.whl.metadata\n",
      "  Using cached grpcio_status-1.57.0-py3-none-any.whl.metadata (1.2 kB)\n",
      "  Obtaining dependency information for grpcio-status>=1.33.2 from https://files.pythonhosted.org/packages/ef/16/3018689d96918e9c4c7407adf96b721df4d6748ba65db82c5eaa63564335/grpcio_status-1.56.2-py3-none-any.whl.metadata\n",
      "  Using cached grpcio_status-1.56.2-py3-none-any.whl.metadata (1.3 kB)\n",
      "  Obtaining dependency information for grpcio-status>=1.33.2 from https://files.pythonhosted.org/packages/2b/21/aaff30111c5941fd9adb5abbf06e04a0e491a685f48ffb291f72ad595ec7/grpcio_status-1.56.0-py3-none-any.whl.metadata\n",
      "  Using cached grpcio_status-1.56.0-py3-none-any.whl.metadata (1.3 kB)\n",
      "  Obtaining dependency information for grpcio-status>=1.33.2 from https://files.pythonhosted.org/packages/b6/c8/0efd0cf1ff62b3acc28619b9ba80a6ead4eb0ee42bb1c3b3841610af98a7/grpcio_status-1.55.3-py3-none-any.whl.metadata\n",
      "  Using cached grpcio_status-1.55.3-py3-none-any.whl.metadata (1.3 kB)\n",
      "  Obtaining dependency information for grpcio-status>=1.33.2 from https://files.pythonhosted.org/packages/b9/ad/51cf59eb26ffa5360ba9dc318580b777e5dda1aa344ad34475103d97e5ac/grpcio_status-1.54.3-py3-none-any.whl.metadata\n",
      "  Using cached grpcio_status-1.54.3-py3-none-any.whl.metadata (1.3 kB)\n",
      "  Obtaining dependency information for grpcio-status>=1.33.2 from https://files.pythonhosted.org/packages/5f/06/19520e0c6ab22fe09a0c8cfeabdf63b1ce6ea5d6ac88a65a2fa57b080976/grpcio_status-1.54.2-py3-none-any.whl.metadata\n",
      "  Using cached grpcio_status-1.54.2-py3-none-any.whl.metadata (1.3 kB)\n",
      "  Using cached grpcio_status-1.54.0-py3-none-any.whl (5.1 kB)\n",
      "INFO: pip is still looking at multiple versions of grpcio-status to determine which version is compatible with other requirements. This could take a while.\n",
      "  Obtaining dependency information for grpcio-status>=1.33.2 from https://files.pythonhosted.org/packages/fb/c0/8ee53675cb1aecaa7fcbc9bea6575cb8c19a21dd0ce80fe6e5edb04426f4/grpcio_status-1.53.2-py3-none-any.whl.metadata\n",
      "  Using cached grpcio_status-1.53.2-py3-none-any.whl.metadata (1.3 kB)\n",
      "  Obtaining dependency information for grpcio-status>=1.33.2 from https://files.pythonhosted.org/packages/61/14/6a4476403abaf954c0b5715de9cfdb7528143c5ac372316fa95704ae8551/grpcio_status-1.53.1-py3-none-any.whl.metadata\n",
      "  Using cached grpcio_status-1.53.1-py3-none-any.whl.metadata (1.3 kB)\n",
      "  Using cached grpcio_status-1.53.0-py3-none-any.whl (5.1 kB)\n",
      "  Using cached grpcio_status-1.51.3-py3-none-any.whl (5.1 kB)\n",
      "  Using cached grpcio_status-1.51.1-py3-none-any.whl (5.1 kB)\n",
      "INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.\n",
      "  Using cached grpcio_status-1.50.0-py3-none-any.whl (14 kB)\n",
      "  Using cached grpcio_status-1.49.1-py3-none-any.whl (14 kB)\n",
      "  Using cached grpcio_status-1.48.2-py3-none-any.whl (14 kB)\n",
      "Requirement already satisfied: pyrsistent>=0.14.0 in /opt/conda/lib/python3.8/site-packages (from jsonschema>=2.6->nbformat>=4.2.0->ipywidgets<8,>=7->tensorflow_model_analysis) (0.19.3)\n",
      "Requirement already satisfied: importlib-metadata>=4.8.3 in /opt/conda/lib/python3.8/site-packages (from jupyter-client>=6.1.12->ipykernel>=4.5.1->ipywidgets<8,>=7->tensorflow_model_analysis) (5.2.0)\n",
      "Requirement already satisfied: platformdirs>=2.5 in /opt/conda/lib/python3.8/site-packages (from jupyter-core->nbformat>=4.2.0->ipywidgets<8,>=7->tensorflow_model_analysis) (3.2.0)\n",
      "Requirement already satisfied: jinja2 in /opt/conda/lib/python3.8/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<8,>=7->tensorflow_model_analysis) (3.1.2)\n",
      "Requirement already satisfied: argon2-cffi in /opt/conda/lib/python3.8/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<8,>=7->tensorflow_model_analysis) (21.3.0)\n",
      "Requirement already satisfied: ipython-genutils in /opt/conda/lib/python3.8/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<8,>=7->tensorflow_model_analysis) (0.2.0)\n",
      "Requirement already satisfied: nbconvert>=5 in /opt/conda/lib/python3.8/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<8,>=7->tensorflow_model_analysis) (7.2.10)\n",
      "Requirement already satisfied: Send2Trash>=1.8.0 in /opt/conda/lib/python3.8/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<8,>=7->tensorflow_model_analysis) (1.8.0)\n",
      "Requirement already satisfied: terminado>=0.8.3 in /opt/conda/lib/python3.8/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<8,>=7->tensorflow_model_analysis) (0.17.1)\n",
      "Requirement already satisfied: prometheus-client in /opt/conda/lib/python3.8/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<8,>=7->tensorflow_model_analysis) (0.13.1)\n",
      "Requirement already satisfied: nbclassic>=0.4.7 in /opt/conda/lib/python3.8/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<8,>=7->tensorflow_model_analysis) (0.5.5)\n",
      "Requirement already satisfied: pyasn1>=0.1.7 in /opt/conda/lib/python3.8/site-packages (from oauth2client>=1.4.12->google-apitools<0.5.32,>=0.5.31->apache-beam[gcp]<3,>=2.47->tensorflow_model_analysis) (0.5.0)\n",
      "Requirement already satisfied: MarkupSafe>=2.1.1 in /opt/conda/lib/python3.8/site-packages (from werkzeug>=1.0.1->tensorboard<2.14,>=2.13->tensorflow<3,>=2.13->tensorflow_model_analysis) (2.1.2)\n",
      "Requirement already satisfied: zipp>=0.5 in /opt/conda/lib/python3.8/site-packages (from importlib-metadata>=4.8.3->jupyter-client>=6.1.12->ipykernel>=4.5.1->ipywidgets<8,>=7->tensorflow_model_analysis) (3.15.0)\n",
      "Requirement already satisfied: jupyter-server>=1.8 in /opt/conda/lib/python3.8/site-packages (from nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<8,>=7->tensorflow_model_analysis) (1.24.0)\n",
      "Requirement already satisfied: notebook-shim>=0.1.0 in /opt/conda/lib/python3.8/site-packages (from nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<8,>=7->tensorflow_model_analysis) (0.2.2)\n",
      "Requirement already satisfied: beautifulsoup4 in /opt/conda/lib/python3.8/site-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<8,>=7->tensorflow_model_analysis) (4.12.2)\n",
      "Requirement already satisfied: bleach in /opt/conda/lib/python3.8/site-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<8,>=7->tensorflow_model_analysis) (6.0.0)\n",
      "Requirement already satisfied: defusedxml in /opt/conda/lib/python3.8/site-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<8,>=7->tensorflow_model_analysis) (0.7.1)\n",
      "Requirement already satisfied: jupyterlab-pygments in /opt/conda/lib/python3.8/site-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<8,>=7->tensorflow_model_analysis) (0.2.2)\n",
      "Requirement already satisfied: mistune<3,>=2.0.3 in /opt/conda/lib/python3.8/site-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<8,>=7->tensorflow_model_analysis) (2.0.5)\n",
      "Requirement already satisfied: nbclient>=0.5.0 in /opt/conda/lib/python3.8/site-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<8,>=7->tensorflow_model_analysis) (0.7.3)\n",
      "Requirement already satisfied: pandocfilters>=1.4.1 in /opt/conda/lib/python3.8/site-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<8,>=7->tensorflow_model_analysis) (1.5.0)\n",
      "Requirement already satisfied: tinycss2 in /opt/conda/lib/python3.8/site-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<8,>=7->tensorflow_model_analysis) (1.2.1)\n",
      "Requirement already satisfied: oauthlib>=3.0.0 in /opt/conda/lib/python3.8/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<1.1,>=0.5->tensorboard<2.14,>=2.13->tensorflow<3,>=2.13->tensorflow_model_analysis) (3.2.2)\n",
      "Requirement already satisfied: argon2-cffi-bindings in /opt/conda/lib/python3.8/site-packages (from argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<8,>=7->tensorflow_model_analysis) (21.2.0)\n",
      "Requirement already satisfied: anyio<4,>=3.1.0 in /opt/conda/lib/python3.8/site-packages (from jupyter-server>=1.8->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<8,>=7->tensorflow_model_analysis) (3.6.2)\n",
      "Requirement already satisfied: websocket-client in /opt/conda/lib/python3.8/site-packages (from jupyter-server>=1.8->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<8,>=7->tensorflow_model_analysis) (1.5.1)\n",
      "Requirement already satisfied: cffi>=1.0.1 in /opt/conda/lib/python3.8/site-packages (from argon2-cffi-bindings->argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<8,>=7->tensorflow_model_analysis) (1.14.6)\n",
      "Requirement already satisfied: soupsieve>1.2 in /opt/conda/lib/python3.8/site-packages (from beautifulsoup4->nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<8,>=7->tensorflow_model_analysis) (2.4.1)\n",
      "Requirement already satisfied: webencodings in /opt/conda/lib/python3.8/site-packages (from bleach->nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<8,>=7->tensorflow_model_analysis) (0.5.1)\n",
      "Requirement already satisfied: sniffio>=1.1 in /opt/conda/lib/python3.8/site-packages (from anyio<4,>=3.1.0->jupyter-server>=1.8->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<8,>=7->tensorflow_model_analysis) (1.3.0)\n",
      "Requirement already satisfied: pycparser in /opt/conda/lib/python3.8/site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<8,>=7->tensorflow_model_analysis) (2.21)\n",
      "Using cached tensorflow_model_analysis-0.45.0-py3-none-any.whl (1.9 MB)\n"
     ]
    }
   ],
   "source": [
    "!pip install tensorflow_model_analysis"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a556faa7-7307-456d-8e4c-958c7814168c",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Import the required packages "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "13b6b550-10b2-4c13-9640-1c4c87288b82",
   "metadata": {},
   "outputs": [
    {
     "ename": "ModuleNotFoundError",
     "evalue": "No module named 'tensorflow_model_analysis'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[1], line 6\u001b[0m\n\u001b[1;32m      3\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;21;01murllib\u001b[39;00m\n\u001b[1;32m      4\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;21;01mpandas\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m \u001b[38;5;21;01mpd\u001b[39;00m\n\u001b[0;32m----> 6\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;21;01mtensorflow_model_analysis\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m \u001b[38;5;21;01mtfma\u001b[39;00m\n\u001b[1;32m      7\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mtfx\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01morchestration\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mexperimental\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01minteractive\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01minteractive_context\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m InteractiveContext\n",
      "\u001b[0;31mModuleNotFoundError\u001b[0m: No module named 'tensorflow_model_analysis'"
     ]
    }
   ],
   "source": [
    "import os\n",
    "import tempfile\n",
    "import urllib\n",
    "import pandas as pd\n",
    "\n",
    "import tensorflow_model_analysis as tfma\n",
    "from tfx.orchestration.experimental.interactive.interactive_context import InteractiveContext"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f9366475-6c3c-4f32-8358-07be456d42af",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
